// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: appointments.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
    first_name,
    last_name,
    email,
    mobile_phone,
    requested_date,
    requested_time,
    is_emergency,
    description,
    appointment_type,
    is_scheduled,
    scheduled_date,
    scheduled_time,
    is_cancelled,
    duration_minutes,
    created_by,
    scheduled_by,
    practice_id,
    provider_id,
    location_id,
    patient_id,
    token
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
RETURNING id, created_at, modified_at, first_name, last_name, email, mobile_phone, requested_date, requested_time, is_emergency, description, appointment_type, is_scheduled, scheduled_date, scheduled_time, is_cancelled, duration_minutes, created_by, scheduled_by, practice_id, provider_id, location_id, patient_id, token, deleted_at
`

type CreateAppointmentParams struct {
	FirstName       string
	LastName        string
	Email           string
	MobilePhone     string
	RequestedDate   *time.Time
	RequestedTime   string
	IsEmergency     bool
	Description     *string
	AppointmentType *string
	IsScheduled     bool
	ScheduledDate   *time.Time
	ScheduledTime   *string
	IsCancelled     bool
	DurationMinutes *int32
	CreatedBy       *uuid.UUID
	ScheduledBy     *uuid.UUID
	PracticeID      *uuid.UUID
	ProviderID      *uuid.UUID
	LocationID      *uuid.UUID
	PatientID       *uuid.UUID
	Token           string
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
		arg.RequestedDate,
		arg.RequestedTime,
		arg.IsEmergency,
		arg.Description,
		arg.AppointmentType,
		arg.IsScheduled,
		arg.ScheduledDate,
		arg.ScheduledTime,
		arg.IsCancelled,
		arg.DurationMinutes,
		arg.CreatedBy,
		arg.ScheduledBy,
		arg.PracticeID,
		arg.ProviderID,
		arg.LocationID,
		arg.PatientID,
		arg.Token,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.RequestedDate,
		&i.RequestedTime,
		&i.IsEmergency,
		&i.Description,
		&i.AppointmentType,
		&i.IsScheduled,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.IsCancelled,
		&i.DurationMinutes,
		&i.CreatedBy,
		&i.ScheduledBy,
		&i.PracticeID,
		&i.ProviderID,
		&i.LocationID,
		&i.PatientID,
		&i.Token,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :one
DELETE FROM appointments
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteAppointment(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAppointment, id)
	err := row.Scan(&id)
	return id, err
}

const getAppointmentById = `-- name: GetAppointmentById :one
SELECT id, created_at, modified_at, first_name, last_name, email, mobile_phone, requested_date, requested_time, is_emergency, description, appointment_type, is_scheduled, scheduled_date, scheduled_time, is_cancelled, duration_minutes, created_by, scheduled_by, practice_id, provider_id, location_id, patient_id, token, deleted_at FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointmentById(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentById, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.RequestedDate,
		&i.RequestedTime,
		&i.IsEmergency,
		&i.Description,
		&i.AppointmentType,
		&i.IsScheduled,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.IsCancelled,
		&i.DurationMinutes,
		&i.CreatedBy,
		&i.ScheduledBy,
		&i.PracticeID,
		&i.ProviderID,
		&i.LocationID,
		&i.PatientID,
		&i.Token,
		&i.DeletedAt,
	)
	return i, err
}

const getAppointments = `-- name: GetAppointments :many
SELECT id, created_at, modified_at, first_name, last_name, email, mobile_phone, requested_date, requested_time, is_emergency, description, appointment_type, is_scheduled, scheduled_date, scheduled_time, is_cancelled, duration_minutes, created_by, scheduled_by, practice_id, provider_id, location_id, patient_id, token, deleted_at FROM appointments
`

func (q *Queries) GetAppointments(ctx context.Context) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.MobilePhone,
			&i.RequestedDate,
			&i.RequestedTime,
			&i.IsEmergency,
			&i.Description,
			&i.AppointmentType,
			&i.IsScheduled,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.IsCancelled,
			&i.DurationMinutes,
			&i.CreatedBy,
			&i.ScheduledBy,
			&i.PracticeID,
			&i.ProviderID,
			&i.LocationID,
			&i.PatientID,
			&i.Token,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageAppointmentByToken = `-- name: ManageAppointmentByToken :one
UPDATE appointments
SET
    requested_date = COALESCE($1, requested_date),
    requested_time = COALESCE($2, requested_time),
    is_cancelled = COALESCE($3, is_cancelled),
    is_emergency = COALESCE($4, is_emergency),
    description = COALESCE($5, description),
    appointment_type = COALESCE($6, appointment_type),
    modified_at = NOW()
WHERE token = $7
RETURNING id, created_at, modified_at, first_name, last_name, email, mobile_phone, requested_date, requested_time, is_emergency, description, appointment_type, is_scheduled, scheduled_date, scheduled_time, is_cancelled, duration_minutes, created_by, scheduled_by, practice_id, provider_id, location_id, patient_id, token, deleted_at
`

type ManageAppointmentByTokenParams struct {
	RequestedDate   *time.Time
	RequestedTime   *string
	IsCancelled     *bool
	IsEmergency     *bool
	Description     *string
	AppointmentType *string
	Token           string
}

func (q *Queries) ManageAppointmentByToken(ctx context.Context, arg ManageAppointmentByTokenParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, manageAppointmentByToken,
		arg.RequestedDate,
		arg.RequestedTime,
		arg.IsCancelled,
		arg.IsEmergency,
		arg.Description,
		arg.AppointmentType,
		arg.Token,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.RequestedDate,
		&i.RequestedTime,
		&i.IsEmergency,
		&i.Description,
		&i.AppointmentType,
		&i.IsScheduled,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.IsCancelled,
		&i.DurationMinutes,
		&i.CreatedBy,
		&i.ScheduledBy,
		&i.PracticeID,
		&i.ProviderID,
		&i.LocationID,
		&i.PatientID,
		&i.Token,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteAppointment = `-- name: SoftDeleteAppointment :one
UPDATE appointments
SET
    deleted_at = NOW()
WHERE id = $1
    AND practice_id = $2
    AND is_scheduled = false
    AND is_cancelled = false
    AND deleted_at IS NULL
RETURNING id, created_at, modified_at, first_name, last_name, email, mobile_phone, requested_date, requested_time, is_emergency, description, appointment_type, is_scheduled, scheduled_date, scheduled_time, is_cancelled, duration_minutes, created_by, scheduled_by, practice_id, provider_id, location_id, patient_id, token, deleted_at
`

type SoftDeleteAppointmentParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) SoftDeleteAppointment(ctx context.Context, arg SoftDeleteAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, softDeleteAppointment, arg.ID, arg.PracticeID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.RequestedDate,
		&i.RequestedTime,
		&i.IsEmergency,
		&i.Description,
		&i.AppointmentType,
		&i.IsScheduled,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.IsCancelled,
		&i.DurationMinutes,
		&i.CreatedBy,
		&i.ScheduledBy,
		&i.PracticeID,
		&i.ProviderID,
		&i.LocationID,
		&i.PatientID,
		&i.Token,
		&i.DeletedAt,
	)
	return i, err
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments
SET
    scheduled_date = COALESCE($1, scheduled_date),
    scheduled_time = COALESCE($2, scheduled_time),
    is_scheduled = COALESCE($3, is_scheduled),
    is_cancelled = COALESCE($4, is_cancelled),
    provider_id = COALESCE($5, provider_id),
    location_id = COALESCE($6, location_id),
    duration_minutes = COALESCE($7, duration_minutes),
    modified_at = NOW()
WHERE id = $8
    AND practice_id = $9
    AND deleted_at IS NULL
RETURNING id, created_at, modified_at, first_name, last_name, email, mobile_phone, requested_date, requested_time, is_emergency, description, appointment_type, is_scheduled, scheduled_date, scheduled_time, is_cancelled, duration_minutes, created_by, scheduled_by, practice_id, provider_id, location_id, patient_id, token, deleted_at
`

type UpdateAppointmentParams struct {
	ScheduledDate   *time.Time
	ScheduledTime   *string
	IsScheduled     *bool
	IsCancelled     *bool
	ProviderID      *uuid.UUID
	LocationID      *uuid.UUID
	DurationMinutes *int32
	ID              uuid.UUID
	PracticeID      uuid.UUID
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointment,
		arg.ScheduledDate,
		arg.ScheduledTime,
		arg.IsScheduled,
		arg.IsCancelled,
		arg.ProviderID,
		arg.LocationID,
		arg.DurationMinutes,
		arg.ID,
		arg.PracticeID,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.RequestedDate,
		&i.RequestedTime,
		&i.IsEmergency,
		&i.Description,
		&i.AppointmentType,
		&i.IsScheduled,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.IsCancelled,
		&i.DurationMinutes,
		&i.CreatedBy,
		&i.ScheduledBy,
		&i.PracticeID,
		&i.ProviderID,
		&i.LocationID,
		&i.PatientID,
		&i.Token,
		&i.DeletedAt,
	)
	return i, err
}
