// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: connected_apps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getConnectedApps = `-- name: GetConnectedApps :many
SELECT id, created_at, updated_at, practice_id, provider, connected_account_email, access_token, refresh_token, token_expires_at, is_connected, last_error FROM connected_apps WHERE practice_id = $1
`

func (q *Queries) GetConnectedApps(ctx context.Context, practiceID uuid.UUID) ([]ConnectedApp, error) {
	rows, err := q.db.Query(ctx, getConnectedApps, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectedApp
	for rows.Next() {
		var i ConnectedApp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PracticeID,
			&i.Provider,
			&i.ConnectedAccountEmail,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.IsConnected,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
