// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: connected_apps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getConnectedApps = `-- name: GetConnectedApps :many
SELECT provider, connected_account_email, is_connected
FROM connected_apps
WHERE practice_id = $1
`

type GetConnectedAppsRow struct {
	Provider              string
	ConnectedAccountEmail *string
	IsConnected           bool
}

func (q *Queries) GetConnectedApps(ctx context.Context, practiceID uuid.UUID) ([]GetConnectedAppsRow, error) {
	rows, err := q.db.Query(ctx, getConnectedApps, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConnectedAppsRow
	for rows.Next() {
		var i GetConnectedAppsRow
		if err := rows.Scan(&i.Provider, &i.ConnectedAccountEmail, &i.IsConnected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
