// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exports.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDataExportAuditLog = `-- name: CreateDataExportAuditLog :exec
INSERT INTO data_export_audit_log (
    practice_id, exported_by_user_id, export_type, row_count
) VALUES (
    $1, $2,
    $3, $4
)
`

type CreateDataExportAuditLogParams struct {
	PracticeID       uuid.UUID
	ExportedByUserID uuid.UUID
	ExportType       string
	RowCount         int32
}

func (q *Queries) CreateDataExportAuditLog(ctx context.Context, arg CreateDataExportAuditLogParams) error {
	_, err := q.db.Exec(ctx, createDataExportAuditLog,
		arg.PracticeID,
		arg.ExportedByUserID,
		arg.ExportType,
		arg.RowCount,
	)
	return err
}

const listAppointmentExportRows = `-- name: ListAppointmentExportRows :many
SELECT a.first_name, a.last_name, a.email, a.mobile_phone,
       a.appointment_type, a.requested_date, a.is_scheduled, a.is_cancelled,
       l.name AS location_name, a.description, a.created_at
FROM appointments a
LEFT JOIN practice_locations l
  ON l.id = a.location_id AND l.practice_id = a.practice_id
WHERE a.practice_id = $1
  AND a.deleted_at IS NULL
ORDER BY a.created_at DESC, a.id DESC
LIMIT 10001
`

type ListAppointmentExportRowsRow struct {
	FirstName       string
	LastName        string
	Email           string
	MobilePhone     string
	AppointmentType *string
	RequestedDate   *time.Time
	IsScheduled     bool
	IsCancelled     bool
	LocationName    *string
	Description     *string
	CreatedAt       time.Time
}

func (q *Queries) ListAppointmentExportRows(ctx context.Context, practiceID uuid.UUID) ([]ListAppointmentExportRowsRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentExportRows, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentExportRowsRow
	for rows.Next() {
		var i ListAppointmentExportRowsRow
		if err := rows.Scan(
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.MobilePhone,
			&i.AppointmentType,
			&i.RequestedDate,
			&i.IsScheduled,
			&i.IsCancelled,
			&i.LocationName,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationExportRows = `-- name: ListRegistrationExportRows :many
SELECT r.id, r.patient_name, r.patient_email, r.patient_phone,
       r.completed_at, COALESCE(d.form_version, '')::text AS form_version,
       COALESCE(d.form_data, '{}'::jsonb)::jsonb AS form_data
FROM patient_registrations r
LEFT JOIN LATERAL (
    SELECT form_version, form_data
    FROM patient_registration_data
    WHERE registration_id = r.id
    ORDER BY submitted_at DESC, id DESC
    LIMIT 1
) d ON TRUE
WHERE r.practice_id = $1
  AND r.status = 'completed'
  AND r.deleted_at IS NULL
ORDER BY r.completed_at DESC NULLS LAST, r.id DESC
LIMIT 1001
`

type ListRegistrationExportRowsRow struct {
	ID           uuid.UUID
	PatientName  string
	PatientEmail *string
	PatientPhone *string
	CompletedAt  *time.Time
	FormVersion  string
	FormData     []byte
}

func (q *Queries) ListRegistrationExportRows(ctx context.Context, practiceID uuid.UUID) ([]ListRegistrationExportRowsRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationExportRows, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationExportRowsRow
	for rows.Next() {
		var i ListRegistrationExportRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientName,
			&i.PatientEmail,
			&i.PatientPhone,
			&i.CompletedAt,
			&i.FormVersion,
			&i.FormData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
