// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invites.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePracticeInvite = `-- name: DeletePracticeInvite :execrows
DELETE FROM practice_invites
WHERE id = $1 AND practice_id = $2
`

type DeletePracticeInviteParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) DeletePracticeInvite(ctx context.Context, arg DeletePracticeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePracticeInvite, arg.ID, arg.PracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPracticeUserByEmail = `-- name: FindPracticeUserByEmail :one
SELECT id FROM users
WHERE practice_id = $1
  AND lower(email) = lower($2)
  AND deleted_at IS NULL
LIMIT 1
`

type FindPracticeUserByEmailParams struct {
	PracticeID *uuid.UUID
	Email      string
}

func (q *Queries) FindPracticeUserByEmail(ctx context.Context, arg FindPracticeUserByEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findPracticeUserByEmail, arg.PracticeID, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getInviteValidation = `-- name: GetInviteValidation :one
SELECT i.id, i.first_name, i.last_name, i.email, i.role, i.org_role,
       i.token_expires_at, i.accepted_at, p.name AS practice_name
FROM practice_invites i
JOIN practices p ON p.id = i.practice_id
WHERE i.token = $1
`

type GetInviteValidationRow struct {
	ID             uuid.UUID
	FirstName      string
	LastName       string
	Email          string
	Role           string
	OrgRole        *string
	TokenExpiresAt time.Time
	AcceptedAt     *time.Time
	PracticeName   string
}

func (q *Queries) GetInviteValidation(ctx context.Context, token string) (GetInviteValidationRow, error) {
	row := q.db.QueryRow(ctx, getInviteValidation, token)
	var i GetInviteValidationRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.OrgRole,
		&i.TokenExpiresAt,
		&i.AcceptedAt,
		&i.PracticeName,
	)
	return i, err
}

const getPracticeInviteForResend = `-- name: GetPracticeInviteForResend :one
SELECT i.id, i.email, i.first_name, i.last_name, i.role, i.org_role,
       p.name AS practice_name
FROM practice_invites i
JOIN practices p ON p.id = i.practice_id
WHERE i.id = $1
  AND i.practice_id = $2
  AND i.accepted_at IS NULL
`

type GetPracticeInviteForResendParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

type GetPracticeInviteForResendRow struct {
	ID           uuid.UUID
	Email        string
	FirstName    string
	LastName     string
	Role         string
	OrgRole      *string
	PracticeName string
}

func (q *Queries) GetPracticeInviteForResend(ctx context.Context, arg GetPracticeInviteForResendParams) (GetPracticeInviteForResendRow, error) {
	row := q.db.QueryRow(ctx, getPracticeInviteForResend, arg.ID, arg.PracticeID)
	var i GetPracticeInviteForResendRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.OrgRole,
		&i.PracticeName,
	)
	return i, err
}

const getPracticeNameForInvite = `-- name: GetPracticeNameForInvite :one
SELECT name FROM practices WHERE id = $1
`

func (q *Queries) GetPracticeNameForInvite(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPracticeNameForInvite, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listPracticeInvites = `-- name: ListPracticeInvites :many
SELECT id, first_name, last_name, email, role, org_role, created_at, token_expires_at
FROM practice_invites
WHERE practice_id = $1
  AND accepted_at IS NULL
  AND token_expires_at > NOW()
ORDER BY created_at DESC, id DESC
`

type ListPracticeInvitesRow struct {
	ID             uuid.UUID
	FirstName      string
	LastName       string
	Email          string
	Role           string
	OrgRole        *string
	CreatedAt      time.Time
	TokenExpiresAt time.Time
}

func (q *Queries) ListPracticeInvites(ctx context.Context, practiceID uuid.UUID) ([]ListPracticeInvitesRow, error) {
	rows, err := q.db.Query(ctx, listPracticeInvites, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPracticeInvitesRow
	for rows.Next() {
		var i ListPracticeInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.OrgRole,
			&i.CreatedAt,
			&i.TokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotatePracticeInvite = `-- name: RotatePracticeInvite :execrows
UPDATE practice_invites
SET token = $1, token_expires_at = $2
WHERE id = $3
  AND practice_id = $4
  AND accepted_at IS NULL
`

type RotatePracticeInviteParams struct {
	Token          string
	TokenExpiresAt time.Time
	ID             uuid.UUID
	PracticeID     uuid.UUID
}

func (q *Queries) RotatePracticeInvite(ctx context.Context, arg RotatePracticeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotatePracticeInvite,
		arg.Token,
		arg.TokenExpiresAt,
		arg.ID,
		arg.PracticeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPracticeInvite = `-- name: UpsertPracticeInvite :one
INSERT INTO practice_invites (
    practice_id, email, first_name, last_name, org_role, role,
    invited_by, token, token_expires_at, accepted_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, NULL
)
ON CONFLICT (practice_id, email) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    org_role = EXCLUDED.org_role,
    role = EXCLUDED.role,
    invited_by = EXCLUDED.invited_by,
    token = EXCLUDED.token,
    token_expires_at = EXCLUDED.token_expires_at,
    accepted_at = NULL
RETURNING id, token, token_expires_at
`

type UpsertPracticeInviteParams struct {
	PracticeID     uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	OrgRole        *string
	Role           string
	InvitedBy      uuid.UUID
	Token          string
	TokenExpiresAt time.Time
}

type UpsertPracticeInviteRow struct {
	ID             uuid.UUID
	Token          string
	TokenExpiresAt time.Time
}

func (q *Queries) UpsertPracticeInvite(ctx context.Context, arg UpsertPracticeInviteParams) (UpsertPracticeInviteRow, error) {
	row := q.db.QueryRow(ctx, upsertPracticeInvite,
		arg.PracticeID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.OrgRole,
		arg.Role,
		arg.InvitedBy,
		arg.Token,
		arg.TokenExpiresAt,
	)
	var i UpsertPracticeInviteRow
	err := row.Scan(&i.ID, &i.Token, &i.TokenExpiresAt)
	return i, err
}
