// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	ModifiedAt      time.Time
	FirstName       string
	LastName        string
	Email           string
	MobilePhone     string
	RequestedDate   time.Time
	RequestedTime   string
	IsEmergency     bool
	Description     *string
	AppointmentType string
	IsScheduled     bool
	ScheduledDate   *time.Time
	ScheduledTime   *string
	IsCancelled     bool
	DurationMinutes *int32
	CreatedBy       *uuid.UUID
	ScheduledBy     *uuid.UUID
	PracticeID      uuid.UUID
	ProviderID      *uuid.UUID
	LocationID      *uuid.UUID
	PatientID       *uuid.UUID
	Token           string
	DeletedAt       *time.Time
}

type AppointmentCalendarEvent struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AppointmentID   uuid.UUID
	Provider        string
	ExternalEventID string
}

type ConnectedApp struct {
	ID                    uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	PracticeID            uuid.UUID
	Provider              string
	ConnectedAccountEmail *string
	AccessToken           *string
	RefreshToken          *string
	TokenExpiresAt        *time.Time
	IsConnected           bool
	LastError             *string
}

type NotificationLog struct {
	ID               uuid.UUID
	SentAt           time.Time
	PracticeID       uuid.UUID
	Channel          string
	NotificationType string
}

type Patient struct {
	ID                    uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	PracticeID            uuid.UUID
	FirstName             string
	LastName              string
	Email                 *string
	MobilePhone           *string
	HomePhone             *string
	DateOfBirth           *time.Time
	AddressLine1          *string
	AddressLine2          *string
	City                  *string
	EmailConsent          bool
	WhatsappConsent       bool
	EmergencyContactName  *string
	EmergencyContactPhone *string
	Notes                 *string
}

type PatientRegistration struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	PracticeID     uuid.UUID
	AppointmentID  *uuid.UUID
	PatientID      *uuid.UUID
	PatientName    string
	PatientEmail   string
	Token          string
	TokenExpiresAt time.Time
	Status         string
	SentByUserID   uuid.UUID
	SentAt         *time.Time
	CompletedAt    *time.Time
	DeletedAt      *time.Time
}

type PatientRegistrationDatum struct {
	ID             uuid.UUID
	SubmittedAt    time.Time
	RegistrationID uuid.UUID
	FormVersion    string
	FormData       []byte
}

type Practice struct {
	ID                   uuid.UUID
	CreatedAt            *time.Time
	ModifiedAt           time.Time
	Name                 string
	City                 string
	Phone                *string
	Email                *string
	PracticeCode         string
	Logo                 *string
	StreetAddress        *string
	Facebook             *string
	Instagram            *string
	Website              *string
	HasMultipleProviders bool
	Specialty            *string
	IsSuspended          bool
	PracticeCategory     string
	IsActive             bool
}

type PracticeInvite struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	PracticeID     uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	OrgRole        *string
	Role           string
	InvitedBy      uuid.UUID
	Token          string
	TokenExpiresAt time.Time
	AcceptedAt     *time.Time
}

type PracticeLocation struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	DeletedAt  *time.Time
	PracticeID uuid.UUID
	Name       string
	Address    string
	IsActive   bool
	SortOrder  int32
}

type PracticeProvider struct {
	ID         uuid.UUID
	CreatedAt  *time.Time
	PracticeID uuid.UUID
	ProviderID uuid.UUID
	IsMain     bool
}

type PracticeSetting struct {
	ID                          uuid.UUID
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	PracticeID                  uuid.UUID
	DentalHistoryEnabled        bool
	TmjHistoryEnabled           bool
	MultipleLocationsEnabled    bool
	OptometryHistoryEnabled     bool
	PhysiotherapyHistoryEnabled bool
	CustomFormSections          []byte
	Theme                       string
	ThemeColors                 []byte
}

type ProcedureType struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	DeletedAt  *time.Time
	PracticeID uuid.UUID
	Name       string
	Value      string
	IsActive   bool
	IsDefault  bool
	IsPrimary  bool
	SortOrder  int32
}

type Provider struct {
	ID        uuid.UUID
	CreatedAt *time.Time
	FirstName string
	LastName  string
	Title     *string
	Specialty string
}

type Subscription struct {
	ID                   uuid.UUID
	Plan                 string
	ReferenceId          string
	StripeCustomerId     *string
	StripeSubscriptionId *string
	Status               string
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	TrialStart           pgtype.Timestamptz
	TrialEnd             pgtype.Timestamptz
	CancelAtPeriodEnd    *bool
	CancelAt             pgtype.Timestamptz
	CanceledAt           pgtype.Timestamptz
	EndedAt              pgtype.Timestamptz
	Seats                *int32
	BillingInterval      *string
	StripeScheduleId     *string
}

type User struct {
	ID                           uuid.UUID
	CreatedAt                    *time.Time
	ModifiedAt                   *time.Time
	FirstName                    string
	LastName                     string
	MobilePhone                  *string
	Email                        *string
	PracticeID                   *uuid.UUID
	Role                         *string
	OrgRole                      *string
	IsActive                     bool
	InvitedBy                    *uuid.UUID
	AvatarUrl                    *string
	WhatsappNotificationsEnabled bool
	TermsAgreedAt                *time.Time
	DeletedAt                    *time.Time
}
