// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNotificationLog = `-- name: CreateNotificationLog :exec
INSERT INTO notification_log (practice_id, channel, notification_type)
VALUES ($1, $2, $3)
`

type CreateNotificationLogParams struct {
	PracticeID       uuid.UUID
	Channel          string
	NotificationType string
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) error {
	_, err := q.db.Exec(ctx, createNotificationLog, arg.PracticeID, arg.Channel, arg.NotificationType)
	return err
}

const getNotificationAppointmentContext = `-- name: GetNotificationAppointmentContext :one
SELECT p.id AS practice_id, p.name AS practice_name, p.email AS practice_email,
       p.phone AS practice_phone, p.logo AS practice_logo,
       a.first_name, a.last_name, a.email, a.mobile_phone,
       a.appointment_type, a.scheduled_date, a.scheduled_time,
       pr.first_name AS provider_first_name, pr.last_name AS provider_last_name,
       l.name AS location_name, l.address AS location_address
FROM appointments a
JOIN practices p ON p.id = a.practice_id
LEFT JOIN provider pr ON pr.id = a.provider_id
LEFT JOIN practice_locations l ON l.id = a.location_id
WHERE a.id = $1
  AND a.practice_id = $2
`

type GetNotificationAppointmentContextParams struct {
	AppointmentID uuid.UUID
	PracticeID    uuid.UUID
}

type GetNotificationAppointmentContextRow struct {
	PracticeID        uuid.UUID
	PracticeName      string
	PracticeEmail     *string
	PracticePhone     *string
	PracticeLogo      *string
	FirstName         string
	LastName          string
	Email             string
	MobilePhone       string
	AppointmentType   *string
	ScheduledDate     *time.Time
	ScheduledTime     *string
	ProviderFirstName *string
	ProviderLastName  *string
	LocationName      *string
	LocationAddress   *string
}

func (q *Queries) GetNotificationAppointmentContext(ctx context.Context, arg GetNotificationAppointmentContextParams) (GetNotificationAppointmentContextRow, error) {
	row := q.db.QueryRow(ctx, getNotificationAppointmentContext, arg.AppointmentID, arg.PracticeID)
	var i GetNotificationAppointmentContextRow
	err := row.Scan(
		&i.PracticeID,
		&i.PracticeName,
		&i.PracticeEmail,
		&i.PracticePhone,
		&i.PracticeLogo,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.AppointmentType,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.ProviderFirstName,
		&i.ProviderLastName,
		&i.LocationName,
		&i.LocationAddress,
	)
	return i, err
}

const getNotificationPractice = `-- name: GetNotificationPractice :one
SELECT id, name, email, phone, logo
FROM practices
WHERE id = $1
`

type GetNotificationPracticeRow struct {
	ID    uuid.UUID
	Name  string
	Email *string
	Phone *string
	Logo  *string
}

func (q *Queries) GetNotificationPractice(ctx context.Context, id uuid.UUID) (GetNotificationPracticeRow, error) {
	row := q.db.QueryRow(ctx, getNotificationPractice, id)
	var i GetNotificationPracticeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Logo,
	)
	return i, err
}

const listEligibleNotificationStaffPhones = `-- name: ListEligibleNotificationStaffPhones :many
SELECT mobile_phone
FROM users
WHERE practice_id = $1
  AND mobile_phone IS NOT NULL
  AND whatsapp_notifications_enabled = TRUE
  AND is_active = TRUE
  AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListEligibleNotificationStaffPhones(ctx context.Context, practiceID *uuid.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listEligibleNotificationStaffPhones, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var mobile_phone *string
		if err := rows.Scan(&mobile_phone); err != nil {
			return nil, err
		}
		items = append(items, mobile_phone)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
