// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: onboarding_progress.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listOnboardingProgress = `-- name: ListOnboardingProgress :many
SELECT walkthrough_key, seen_at, dismissed_at, completed_at
FROM onboarding_progress
WHERE user_id = $1
`

type ListOnboardingProgressRow struct {
	WalkthroughKey string
	SeenAt         pgtype.Timestamptz
	DismissedAt    pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

func (q *Queries) ListOnboardingProgress(ctx context.Context, userID uuid.UUID) ([]ListOnboardingProgressRow, error) {
	rows, err := q.db.Query(ctx, listOnboardingProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOnboardingProgressRow
	for rows.Next() {
		var i ListOnboardingProgressRow
		if err := rows.Scan(
			&i.WalkthroughKey,
			&i.SeenAt,
			&i.DismissedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOnboardingProgress = `-- name: UpsertOnboardingProgress :one
INSERT INTO onboarding_progress (
    user_id, walkthrough_key, seen_at, dismissed_at, completed_at, updated_at
) VALUES (
    $1,
    $2,
    CASE WHEN $3::boolean THEN NOW() ELSE NULL END,
    CASE WHEN $4::boolean THEN NOW() ELSE NULL END,
    CASE WHEN $5::boolean THEN NOW() ELSE NULL END,
    NOW()
)
ON CONFLICT (user_id, walkthrough_key) DO UPDATE SET
    seen_at = CASE WHEN $3::boolean THEN NOW() ELSE onboarding_progress.seen_at END,
    dismissed_at = CASE WHEN $4::boolean THEN NOW() ELSE onboarding_progress.dismissed_at END,
    completed_at = CASE WHEN $5::boolean THEN NOW() ELSE onboarding_progress.completed_at END,
    updated_at = NOW()
RETURNING walkthrough_key, seen_at, dismissed_at, completed_at
`

type UpsertOnboardingProgressParams struct {
	UserID         uuid.UUID
	WalkthroughKey string
	SetSeen        bool
	SetDismissed   bool
	SetCompleted   bool
}

type UpsertOnboardingProgressRow struct {
	WalkthroughKey string
	SeenAt         pgtype.Timestamptz
	DismissedAt    pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertOnboardingProgress(ctx context.Context, arg UpsertOnboardingProgressParams) (UpsertOnboardingProgressRow, error) {
	row := q.db.QueryRow(ctx, upsertOnboardingProgress,
		arg.UserID,
		arg.WalkthroughKey,
		arg.SetSeen,
		arg.SetDismissed,
		arg.SetCompleted,
	)
	var i UpsertOnboardingProgressRow
	err := row.Scan(
		&i.WalkthroughKey,
		&i.SeenAt,
		&i.DismissedAt,
		&i.CompletedAt,
	)
	return i, err
}
