// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patients.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findDuplicatePatientEmail = `-- name: FindDuplicatePatientEmail :one
SELECT id FROM patients
WHERE practice_id = $1
  AND id <> $2
  AND email = $3
LIMIT 1
`

type FindDuplicatePatientEmailParams struct {
	PracticeID uuid.UUID
	ID         uuid.UUID
	Email      *string
}

func (q *Queries) FindDuplicatePatientEmail(ctx context.Context, arg FindDuplicatePatientEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDuplicatePatientEmail, arg.PracticeID, arg.ID, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findDuplicatePatientMobilePhone = `-- name: FindDuplicatePatientMobilePhone :one
SELECT id FROM patients
WHERE practice_id = $1
  AND id <> $2
  AND mobile_phone = $3
LIMIT 1
`

type FindDuplicatePatientMobilePhoneParams struct {
	PracticeID  uuid.UUID
	ID          uuid.UUID
	MobilePhone *string
}

func (q *Queries) FindDuplicatePatientMobilePhone(ctx context.Context, arg FindDuplicatePatientMobilePhoneParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDuplicatePatientMobilePhone, arg.PracticeID, arg.ID, arg.MobilePhone)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getLatestPatientRegistration = `-- name: GetLatestPatientRegistration :one
SELECT id, status, sent_at, completed_at, created_at
FROM patient_registrations
WHERE patient_id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestPatientRegistrationParams struct {
	PatientID  *uuid.UUID
	PracticeID uuid.UUID
}

type GetLatestPatientRegistrationRow struct {
	ID          uuid.UUID
	Status      string
	SentAt      *time.Time
	CompletedAt *time.Time
	CreatedAt   time.Time
}

func (q *Queries) GetLatestPatientRegistration(ctx context.Context, arg GetLatestPatientRegistrationParams) (GetLatestPatientRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getLatestPatientRegistration, arg.PatientID, arg.PracticeID)
	var i GetLatestPatientRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SentAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPatient = `-- name: GetPatient :one
SELECT id, created_at, updated_at, practice_id, first_name, last_name, email, mobile_phone, home_phone, date_of_birth, address_line_1, address_line_2, city, email_consent, whatsapp_consent, emergency_contact_name, emergency_contact_phone, notes FROM patients
WHERE id = $1 AND practice_id = $2
`

type GetPatientParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) GetPatient(ctx context.Context, arg GetPatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatient, arg.ID, arg.PracticeID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PracticeID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.HomePhone,
		&i.DateOfBirth,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.EmailConsent,
		&i.WhatsappConsent,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.Notes,
	)
	return i, err
}

const getPatientAppointments = `-- name: GetPatientAppointments :many
SELECT
    id, created_at, modified_at, first_name, last_name, email, mobile_phone,
    requested_date, requested_time, is_emergency, description, appointment_type,
    is_scheduled, scheduled_date, scheduled_time, is_confirmed, is_cancelled,
    duration_minutes, provider_id, location_id, patient_id
FROM appointments
WHERE patient_id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

type GetPatientAppointmentsParams struct {
	PatientID  *uuid.UUID
	PracticeID uuid.UUID
}

type GetPatientAppointmentsRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	ModifiedAt      time.Time
	FirstName       string
	LastName        string
	Email           string
	MobilePhone     string
	RequestedDate   time.Time
	RequestedTime   string
	IsEmergency     bool
	Description     *string
	AppointmentType string
	IsScheduled     bool
	ScheduledDate   *time.Time
	ScheduledTime   *string
	IsConfirmed     bool
	IsCancelled     bool
	DurationMinutes *int32
	ProviderID      *uuid.UUID
	LocationID      *uuid.UUID
	PatientID       *uuid.UUID
}

func (q *Queries) GetPatientAppointments(ctx context.Context, arg GetPatientAppointmentsParams) ([]GetPatientAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, getPatientAppointments, arg.PatientID, arg.PracticeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPatientAppointmentsRow
	for rows.Next() {
		var i GetPatientAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.MobilePhone,
			&i.RequestedDate,
			&i.RequestedTime,
			&i.IsEmergency,
			&i.Description,
			&i.AppointmentType,
			&i.IsScheduled,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.IsConfirmed,
			&i.IsCancelled,
			&i.DurationMinutes,
			&i.ProviderID,
			&i.LocationID,
			&i.PatientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatients = `-- name: ListPatients :many
SELECT id, first_name, last_name, email, mobile_phone, date_of_birth, created_at
FROM patients
WHERE practice_id = $1
  AND (
    $2::text = ''
    OR first_name ILIKE '%' || $2::text || '%'
    OR last_name ILIKE '%' || $2::text || '%'
    OR (first_name || ' ' || last_name) ILIKE '%' || $2::text || '%'
    OR (last_name || ' ' || first_name) ILIKE '%' || $2::text || '%'
    OR email ILIKE '%' || $2::text || '%'
    OR mobile_phone ILIKE '%' || $2::text || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListPatientsParams struct {
	PracticeID  uuid.UUID
	Search      string
	ResultLimit int32
}

type ListPatientsRow struct {
	ID          uuid.UUID
	FirstName   string
	LastName    string
	Email       *string
	MobilePhone *string
	DateOfBirth *time.Time
	CreatedAt   time.Time
}

func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]ListPatientsRow, error) {
	rows, err := q.db.Query(ctx, listPatients, arg.PracticeID, arg.Search, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsRow
	for rows.Next() {
		var i ListPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.MobilePhone,
			&i.DateOfBirth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET
    first_name = CASE WHEN $1::boolean THEN $2::text ELSE first_name END,
    last_name = CASE WHEN $3::boolean THEN $4::text ELSE last_name END,
    email = CASE WHEN $5::boolean THEN $6::text ELSE email END,
    mobile_phone = CASE WHEN $7::boolean THEN $8::text ELSE mobile_phone END,
    home_phone = CASE WHEN $9::boolean THEN $10::text ELSE home_phone END,
    date_of_birth = CASE WHEN $11::boolean THEN $12::date ELSE date_of_birth END,
    address_line_1 = CASE WHEN $13::boolean THEN $14::text ELSE address_line_1 END,
    address_line_2 = CASE WHEN $15::boolean THEN $16::text ELSE address_line_2 END,
    city = CASE WHEN $17::boolean THEN $18::text ELSE city END,
    email_consent = CASE WHEN $19::boolean THEN $20::boolean ELSE email_consent END,
    whatsapp_consent = CASE WHEN $21::boolean THEN $22::boolean ELSE whatsapp_consent END,
    emergency_contact_name = CASE WHEN $23::boolean THEN $24::text ELSE emergency_contact_name END,
    emergency_contact_phone = CASE WHEN $25::boolean THEN $26::text ELSE emergency_contact_phone END,
    notes = CASE WHEN $27::boolean THEN $28::text ELSE notes END,
    updated_at = NOW()
WHERE id = $29 AND practice_id = $30
RETURNING id, created_at, updated_at, practice_id, first_name, last_name, email, mobile_phone, home_phone, date_of_birth, address_line_1, address_line_2, city, email_consent, whatsapp_consent, emergency_contact_name, emergency_contact_phone, notes
`

type UpdatePatientParams struct {
	SetFirstName             bool
	FirstName                string
	SetLastName              bool
	LastName                 string
	SetEmail                 bool
	Email                    *string
	SetMobilePhone           bool
	MobilePhone              *string
	SetHomePhone             bool
	HomePhone                *string
	SetDateOfBirth           bool
	DateOfBirth              *time.Time
	SetAddressLine1          bool
	AddressLine1             *string
	SetAddressLine2          bool
	AddressLine2             *string
	SetCity                  bool
	City                     *string
	SetEmailConsent          bool
	EmailConsent             bool
	SetWhatsappConsent       bool
	WhatsappConsent          bool
	SetEmergencyContactName  bool
	EmergencyContactName     *string
	SetEmergencyContactPhone bool
	EmergencyContactPhone    *string
	SetNotes                 bool
	Notes                    *string
	ID                       uuid.UUID
	PracticeID               uuid.UUID
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.SetFirstName,
		arg.FirstName,
		arg.SetLastName,
		arg.LastName,
		arg.SetEmail,
		arg.Email,
		arg.SetMobilePhone,
		arg.MobilePhone,
		arg.SetHomePhone,
		arg.HomePhone,
		arg.SetDateOfBirth,
		arg.DateOfBirth,
		arg.SetAddressLine1,
		arg.AddressLine1,
		arg.SetAddressLine2,
		arg.AddressLine2,
		arg.SetCity,
		arg.City,
		arg.SetEmailConsent,
		arg.EmailConsent,
		arg.SetWhatsappConsent,
		arg.WhatsappConsent,
		arg.SetEmergencyContactName,
		arg.EmergencyContactName,
		arg.SetEmergencyContactPhone,
		arg.EmergencyContactPhone,
		arg.SetNotes,
		arg.Notes,
		arg.ID,
		arg.PracticeID,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PracticeID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.HomePhone,
		&i.DateOfBirth,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.EmailConsent,
		&i.WhatsappConsent,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.Notes,
	)
	return i, err
}
