// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: practices.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPractice = `-- name: CreatePractice :one
INSERT INTO practices (name, city, phone, email, practice_code, logo, street_address, facebook, instagram, website, has_multiple_providers, specialty, is_suspended, practice_category)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, created_at, modified_at, name, city, phone, email, practice_code, logo, street_address, facebook, instagram, website, has_multiple_providers, specialty, is_suspended, practice_category, is_active
`

type CreatePracticeParams struct {
	Name                 string
	City                 string
	Phone                *string
	Email                *string
	PracticeCode         string
	Logo                 *string
	StreetAddress        *string
	Facebook             *string
	Instagram            *string
	Website              *string
	HasMultipleProviders bool
	Specialty            *string
	IsSuspended          bool
	PracticeCategory     string
}

func (q *Queries) CreatePractice(ctx context.Context, arg CreatePracticeParams) (Practice, error) {
	row := q.db.QueryRow(ctx, createPractice,
		arg.Name,
		arg.City,
		arg.Phone,
		arg.Email,
		arg.PracticeCode,
		arg.Logo,
		arg.StreetAddress,
		arg.Facebook,
		arg.Instagram,
		arg.Website,
		arg.HasMultipleProviders,
		arg.Specialty,
		arg.IsSuspended,
		arg.PracticeCategory,
	)
	var i Practice
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Name,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.PracticeCode,
		&i.Logo,
		&i.StreetAddress,
		&i.Facebook,
		&i.Instagram,
		&i.Website,
		&i.HasMultipleProviders,
		&i.Specialty,
		&i.IsSuspended,
		&i.PracticeCategory,
		&i.IsActive,
	)
	return i, err
}

const getPractice = `-- name: GetPractice :one
SELECT p.id, p.created_at, p.modified_at, p.name, p.city, p.phone, p.email, p.practice_code, p.logo, p.street_address, p.facebook, p.instagram, p.website, p.has_multiple_providers, p.specialty, p.is_suspended, p.practice_category, p.is_active, s.id, s.created_at, s.updated_at, s.practice_id, s.dental_history_enabled, s.tmj_history_enabled, s.multiple_locations_enabled, s.optometry_history_enabled, s.physiotherapy_history_enabled, s.custom_form_sections, s.theme, s.theme_colors, s.available_weekdays
FROM practices p
LEFT JOIN practice_settings s ON s.practice_id = p.id
WHERE p.id = $1
`

type GetPracticeRow struct {
	ID                          uuid.UUID
	CreatedAt                   *time.Time
	ModifiedAt                  time.Time
	Name                        string
	City                        string
	Phone                       *string
	Email                       *string
	PracticeCode                string
	Logo                        *string
	StreetAddress               *string
	Facebook                    *string
	Instagram                   *string
	Website                     *string
	HasMultipleProviders        bool
	Specialty                   *string
	IsSuspended                 bool
	PracticeCategory            string
	IsActive                    bool
	ID_2                        *uuid.UUID
	CreatedAt_2                 *time.Time
	UpdatedAt                   *time.Time
	PracticeID                  *uuid.UUID
	DentalHistoryEnabled        *bool
	TmjHistoryEnabled           *bool
	MultipleLocationsEnabled    *bool
	OptometryHistoryEnabled     *bool
	PhysiotherapyHistoryEnabled *bool
	CustomFormSections          []byte
	Theme                       *string
	ThemeColors                 []byte
	AvailableWeekdays           []int16
}

func (q *Queries) GetPractice(ctx context.Context, id uuid.UUID) (GetPracticeRow, error) {
	row := q.db.QueryRow(ctx, getPractice, id)
	var i GetPracticeRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Name,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.PracticeCode,
		&i.Logo,
		&i.StreetAddress,
		&i.Facebook,
		&i.Instagram,
		&i.Website,
		&i.HasMultipleProviders,
		&i.Specialty,
		&i.IsSuspended,
		&i.PracticeCategory,
		&i.IsActive,
		&i.ID_2,
		&i.CreatedAt_2,
		&i.UpdatedAt,
		&i.PracticeID,
		&i.DentalHistoryEnabled,
		&i.TmjHistoryEnabled,
		&i.MultipleLocationsEnabled,
		&i.OptometryHistoryEnabled,
		&i.PhysiotherapyHistoryEnabled,
		&i.CustomFormSections,
		&i.Theme,
		&i.ThemeColors,
		&i.AvailableWeekdays,
	)
	return i, err
}

const getPracticeByCode = `-- name: GetPracticeByCode :one
SELECT id, created_at, modified_at, name, city, phone, email, practice_code, logo, street_address, facebook, instagram, website, has_multiple_providers, specialty, is_suspended, practice_category, is_active FROM practices
WHERE practice_code = $1
`

func (q *Queries) GetPracticeByCode(ctx context.Context, practiceCode string) (Practice, error) {
	row := q.db.QueryRow(ctx, getPracticeByCode, practiceCode)
	var i Practice
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Name,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.PracticeCode,
		&i.Logo,
		&i.StreetAddress,
		&i.Facebook,
		&i.Instagram,
		&i.Website,
		&i.HasMultipleProviders,
		&i.Specialty,
		&i.IsSuspended,
		&i.PracticeCategory,
		&i.IsActive,
	)
	return i, err
}

const getPracticeProfile = `-- name: GetPracticeProfile :one
SELECT id, name, logo, city, street_address, phone, email, website,
       practice_code, instagram, facebook, has_multiple_providers,
       practice_category, specialty
FROM practices
WHERE id = $1
`

type GetPracticeProfileRow struct {
	ID                   uuid.UUID
	Name                 string
	Logo                 *string
	City                 string
	StreetAddress        *string
	Phone                *string
	Email                *string
	Website              *string
	PracticeCode         string
	Instagram            *string
	Facebook             *string
	HasMultipleProviders bool
	PracticeCategory     string
	Specialty            *string
}

func (q *Queries) GetPracticeProfile(ctx context.Context, id uuid.UUID) (GetPracticeProfileRow, error) {
	row := q.db.QueryRow(ctx, getPracticeProfile, id)
	var i GetPracticeProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.City,
		&i.StreetAddress,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.PracticeCode,
		&i.Instagram,
		&i.Facebook,
		&i.HasMultipleProviders,
		&i.PracticeCategory,
		&i.Specialty,
	)
	return i, err
}

const getPracticeSettingsOverview = `-- name: GetPracticeSettingsOverview :one
SELECT id, name, practice_category, specialty, practice_code, city
FROM practices
WHERE id = $1
`

type GetPracticeSettingsOverviewRow struct {
	ID               uuid.UUID
	Name             string
	PracticeCategory string
	Specialty        *string
	PracticeCode     string
	City             string
}

func (q *Queries) GetPracticeSettingsOverview(ctx context.Context, id uuid.UUID) (GetPracticeSettingsOverviewRow, error) {
	row := q.db.QueryRow(ctx, getPracticeSettingsOverview, id)
	var i GetPracticeSettingsOverviewRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PracticeCategory,
		&i.Specialty,
		&i.PracticeCode,
		&i.City,
	)
	return i, err
}

const getPractices = `-- name: GetPractices :many
SELECT id, created_at, modified_at, name, city, phone, email, practice_code, logo, street_address, facebook, instagram, website, has_multiple_providers, specialty, is_suspended, practice_category, is_active FROM practices
`

func (q *Queries) GetPractices(ctx context.Context) ([]Practice, error) {
	rows, err := q.db.Query(ctx, getPractices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Practice
	for rows.Next() {
		var i Practice
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Name,
			&i.City,
			&i.Phone,
			&i.Email,
			&i.PracticeCode,
			&i.Logo,
			&i.StreetAddress,
			&i.Facebook,
			&i.Instagram,
			&i.Website,
			&i.HasMultipleProviders,
			&i.Specialty,
			&i.IsSuspended,
			&i.PracticeCategory,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchPracticeSettingsPractice = `-- name: PatchPracticeSettingsPractice :execrows
UPDATE practices
SET
    specialty = CASE
        WHEN $1::boolean THEN $2::text
        ELSE specialty
    END,
    has_multiple_providers = CASE
        WHEN $3::boolean THEN $4::boolean
        ELSE has_multiple_providers
    END,
    modified_at = NOW()
WHERE id = $5
`

type PatchPracticeSettingsPracticeParams struct {
	SetSpecialty            bool
	Specialty               *string
	SetHasMultipleProviders bool
	HasMultipleProviders    bool
	ID                      uuid.UUID
}

func (q *Queries) PatchPracticeSettingsPractice(ctx context.Context, arg PatchPracticeSettingsPracticeParams) (int64, error) {
	result, err := q.db.Exec(ctx, patchPracticeSettingsPractice,
		arg.SetSpecialty,
		arg.Specialty,
		arg.SetHasMultipleProviders,
		arg.HasMultipleProviders,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePractice = `-- name: UpdatePractice :one
UPDATE practices
SET
    name = COALESCE($1, name),
    city = COALESCE($2, city),
    phone = COALESCE($3, phone),
    email = COALESCE($4, email),
    practice_code = COALESCE($5, practice_code),
    logo = COALESCE($6, logo),
    street_address = COALESCE($7, street_address),
    facebook = COALESCE($8, facebook),
    instagram = COALESCE($9, instagram),
    website = COALESCE($10, website),
    has_multiple_providers = COALESCE($11, has_multiple_providers),
    specialty = COALESCE($12, specialty),
    is_suspended = COALESCE($13, is_suspended),
    practice_category = COALESCE($14, practice_category),
    is_active = COALESCE($15, is_active),
    modified_at = NOW()
WHERE id = $16
RETURNING id, created_at, modified_at, name, city, phone, email, practice_code, logo, street_address, facebook, instagram, website, has_multiple_providers, specialty, is_suspended, practice_category, is_active
`

type UpdatePracticeParams struct {
	Name                 *string
	City                 *string
	Phone                *string
	Email                *string
	PracticeCode         *string
	Logo                 *string
	StreetAddress        *string
	Facebook             *string
	Instagram            *string
	Website              *string
	HasMultipleProviders *bool
	Specialty            *string
	IsSuspended          *bool
	PracticeCategory     *string
	IsActive             *bool
	ID                   uuid.UUID
}

func (q *Queries) UpdatePractice(ctx context.Context, arg UpdatePracticeParams) (Practice, error) {
	row := q.db.QueryRow(ctx, updatePractice,
		arg.Name,
		arg.City,
		arg.Phone,
		arg.Email,
		arg.PracticeCode,
		arg.Logo,
		arg.StreetAddress,
		arg.Facebook,
		arg.Instagram,
		arg.Website,
		arg.HasMultipleProviders,
		arg.Specialty,
		arg.IsSuspended,
		arg.PracticeCategory,
		arg.IsActive,
		arg.ID,
	)
	var i Practice
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Name,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.PracticeCode,
		&i.Logo,
		&i.StreetAddress,
		&i.Facebook,
		&i.Instagram,
		&i.Website,
		&i.HasMultipleProviders,
		&i.Specialty,
		&i.IsSuspended,
		&i.PracticeCategory,
		&i.IsActive,
	)
	return i, err
}

const updatePracticeCode = `-- name: UpdatePracticeCode :execrows
UPDATE practices
SET practice_code = $1, modified_at = NOW()
WHERE id = $2
`

type UpdatePracticeCodeParams struct {
	PracticeCode string
	ID           uuid.UUID
}

func (q *Queries) UpdatePracticeCode(ctx context.Context, arg UpdatePracticeCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePracticeCode, arg.PracticeCode, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePracticeLogo = `-- name: UpdatePracticeLogo :execrows
UPDATE practices
SET logo = $1, modified_at = NOW()
WHERE id = $2
`

type UpdatePracticeLogoParams struct {
	Logo *string
	ID   uuid.UUID
}

func (q *Queries) UpdatePracticeLogo(ctx context.Context, arg UpdatePracticeLogoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePracticeLogo, arg.Logo, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePracticeProfile = `-- name: UpdatePracticeProfile :execrows
UPDATE practices
SET
    name = $1,
    street_address = $2,
    city = $3,
    phone = $4,
    email = $5,
    website = $6,
    practice_code = $7,
    facebook = $8,
    instagram = $9,
    specialty = $10,
    has_multiple_providers = $11,
    logo = CASE
        WHEN $12::boolean THEN $13::text
        ELSE logo
    END,
    modified_at = NOW()
WHERE id = $14
`

type UpdatePracticeProfileParams struct {
	Name                 string
	StreetAddress        *string
	City                 string
	Phone                *string
	Email                *string
	Website              *string
	PracticeCode         string
	Facebook             *string
	Instagram            *string
	Specialty            *string
	HasMultipleProviders bool
	SetLogo              bool
	Logo                 *string
	ID                   uuid.UUID
}

func (q *Queries) UpdatePracticeProfile(ctx context.Context, arg UpdatePracticeProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePracticeProfile,
		arg.Name,
		arg.StreetAddress,
		arg.City,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.PracticeCode,
		arg.Facebook,
		arg.Instagram,
		arg.Specialty,
		arg.HasMultipleProviders,
		arg.SetLogo,
		arg.Logo,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
