// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: practice_locations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPracticeLocationsByPracticeID = `-- name: GetPracticeLocationsByPracticeID :many
SELECT id, created_at, deleted_at, practice_id, name, address, is_active,
       sort_order, available_weekdays
FROM practice_locations
WHERE practice_id = $1
  AND deleted_at IS NULL
ORDER BY sort_order ASC
`

func (q *Queries) GetPracticeLocationsByPracticeID(ctx context.Context, practiceID uuid.UUID) ([]PracticeLocation, error) {
	rows, err := q.db.Query(ctx, getPracticeLocationsByPracticeID, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PracticeLocation
	for rows.Next() {
		var i PracticeLocation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.PracticeID,
			&i.Name,
			&i.Address,
			&i.IsActive,
			&i.SortOrder,
			&i.AvailableWeekdays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
