// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: practice_procedures.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProcedureType = `-- name: CreateProcedureType :one
INSERT INTO procedure_types (
    practice_id,
    name,
    value,
    is_active,
    is_default,
    is_primary,
    sort_order
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id
`

type CreateProcedureTypeParams struct {
	PracticeID uuid.UUID
	Name       string
	Value      string
	IsActive   bool
	IsDefault  bool
	IsPrimary  bool
	SortOrder  int32
}

func (q *Queries) CreateProcedureType(ctx context.Context, arg CreateProcedureTypeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProcedureType,
		arg.PracticeID,
		arg.Name,
		arg.Value,
		arg.IsActive,
		arg.IsDefault,
		arg.IsPrimary,
		arg.SortOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteProcedureType = `-- name: DeleteProcedureType :exec
UPDATE procedure_types
SET deleted_at = NOW()
WHERE id = $1
AND practice_id = $2
`

type DeleteProcedureTypeParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) DeleteProcedureType(ctx context.Context, arg DeleteProcedureTypeParams) error {
	_, err := q.db.Exec(ctx, deleteProcedureType, arg.ID, arg.PracticeID)
	return err
}

const getProcedureTypesByPracticeID = `-- name: GetProcedureTypesByPracticeID :many
SELECT id, created_at, deleted_at, practice_id, name, value, is_active, is_default, is_primary, sort_order FROM procedure_types
WHERE practice_id = $1
AND deleted_at IS NULL
ORDER BY sort_order ASC
`

func (q *Queries) GetProcedureTypesByPracticeID(ctx context.Context, practiceID uuid.UUID) ([]ProcedureType, error) {
	rows, err := q.db.Query(ctx, getProcedureTypesByPracticeID, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcedureType
	for rows.Next() {
		var i ProcedureType
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.PracticeID,
			&i.Name,
			&i.Value,
			&i.IsActive,
			&i.IsDefault,
			&i.IsPrimary,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcedureType = `-- name: UpdateProcedureType :exec
UPDATE procedure_types
SET
    name       = COALESCE($1, name),
    is_active  = COALESCE($2, is_active),
    sort_order = COALESCE($3, sort_order)
WHERE id = $4
AND practice_id = $5
`

type UpdateProcedureTypeParams struct {
	Name       *string
	IsActive   *bool
	SortOrder  *int32
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) UpdateProcedureType(ctx context.Context, arg UpdateProcedureTypeParams) error {
	_, err := q.db.Exec(ctx, updateProcedureType,
		arg.Name,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
		arg.PracticeID,
	)
	return err
}
