// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: practice_procedures.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const clearPrimaryProcedureType = `-- name: ClearPrimaryProcedureType :exec
UPDATE procedure_types
SET is_primary = FALSE
WHERE practice_id = $1
  AND is_primary = TRUE
`

func (q *Queries) ClearPrimaryProcedureType(ctx context.Context, practiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryProcedureType, practiceID)
	return err
}

const createProcedureType = `-- name: CreateProcedureType :one
INSERT INTO procedure_types (
    practice_id,
    name,
    value,
    is_active,
    is_default,
    is_primary,
    sort_order
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, created_at, deleted_at, practice_id, name, value, is_active,
          is_default, is_primary, sort_order
`

type CreateProcedureTypeParams struct {
	PracticeID uuid.UUID
	Name       string
	Value      string
	IsActive   bool
	IsDefault  bool
	IsPrimary  bool
	SortOrder  int32
}

func (q *Queries) CreateProcedureType(ctx context.Context, arg CreateProcedureTypeParams) (ProcedureType, error) {
	row := q.db.QueryRow(ctx, createProcedureType,
		arg.PracticeID,
		arg.Name,
		arg.Value,
		arg.IsActive,
		arg.IsDefault,
		arg.IsPrimary,
		arg.SortOrder,
	)
	var i ProcedureType
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.PracticeID,
		&i.Name,
		&i.Value,
		&i.IsActive,
		&i.IsDefault,
		&i.IsPrimary,
		&i.SortOrder,
	)
	return i, err
}

const deleteProcedureType = `-- name: DeleteProcedureType :execrows
UPDATE procedure_types
SET deleted_at = NOW()
WHERE id = $1
AND practice_id = $2
`

type DeleteProcedureTypeParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) DeleteProcedureType(ctx context.Context, arg DeleteProcedureTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProcedureType, arg.ID, arg.PracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNextProcedureTypeSortOrder = `-- name: GetNextProcedureTypeSortOrder :one
SELECT (COALESCE(MAX(sort_order), 0) + 1)::integer
FROM procedure_types
WHERE practice_id = $1
`

func (q *Queries) GetNextProcedureTypeSortOrder(ctx context.Context, practiceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextProcedureTypeSortOrder, practiceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getProcedureTypeForMutation = `-- name: GetProcedureTypeForMutation :one
SELECT id, is_default
FROM procedure_types
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
`

type GetProcedureTypeForMutationParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

type GetProcedureTypeForMutationRow struct {
	ID        uuid.UUID
	IsDefault bool
}

func (q *Queries) GetProcedureTypeForMutation(ctx context.Context, arg GetProcedureTypeForMutationParams) (GetProcedureTypeForMutationRow, error) {
	row := q.db.QueryRow(ctx, getProcedureTypeForMutation, arg.ID, arg.PracticeID)
	var i GetProcedureTypeForMutationRow
	err := row.Scan(&i.ID, &i.IsDefault)
	return i, err
}

const getProcedureTypesByPracticeID = `-- name: GetProcedureTypesByPracticeID :many
SELECT id, created_at, deleted_at, practice_id, name, value, is_active, is_default, is_primary, sort_order FROM procedure_types
WHERE practice_id = $1
AND deleted_at IS NULL
ORDER BY sort_order ASC
`

func (q *Queries) GetProcedureTypesByPracticeID(ctx context.Context, practiceID uuid.UUID) ([]ProcedureType, error) {
	rows, err := q.db.Query(ctx, getProcedureTypesByPracticeID, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcedureType
	for rows.Next() {
		var i ProcedureType
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.PracticeID,
			&i.Name,
			&i.Value,
			&i.IsActive,
			&i.IsDefault,
			&i.IsPrimary,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPracticeForProcedureTypeSort = `-- name: LockPracticeForProcedureTypeSort :one
SELECT id
FROM practices
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPracticeForProcedureTypeSort(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPracticeForProcedureTypeSort, id)
	err := row.Scan(&id)
	return id, err
}

const patchProcedureType = `-- name: PatchProcedureType :execrows
UPDATE procedure_types
SET name = CASE
        WHEN $1::boolean THEN $2::text
        ELSE name
    END,
    is_active = CASE
        WHEN $3::boolean THEN $4::boolean
        ELSE is_active
    END,
    sort_order = CASE
        WHEN $5::boolean THEN $6::integer
        ELSE sort_order
    END
WHERE id = $7
AND practice_id = $8
`

type PatchProcedureTypeParams struct {
	SetName      bool
	Name         string
	SetIsActive  bool
	IsActive     bool
	SetSortOrder bool
	SortOrder    int32
	ID           uuid.UUID
	PracticeID   uuid.UUID
}

func (q *Queries) PatchProcedureType(ctx context.Context, arg PatchProcedureTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, patchProcedureType,
		arg.SetName,
		arg.Name,
		arg.SetIsActive,
		arg.IsActive,
		arg.SetSortOrder,
		arg.SortOrder,
		arg.ID,
		arg.PracticeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
