// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: practice_codes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkPracticeCodeExists = `-- name: CheckPracticeCodeExists :one
SELECT id FROM practices where practice_code = $1
`

func (q *Queries) CheckPracticeCodeExists(ctx context.Context, practiceCode string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkPracticeCodeExists, practiceCode)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
