// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: providers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearMainProvider = `-- name: ClearMainProvider :exec
UPDATE practice_provider
SET is_main = FALSE
WHERE practice_id = $1
  AND is_main = TRUE
`

func (q *Queries) ClearMainProvider(ctx context.Context, practiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMainProvider, practiceID)
	return err
}

const createPracticeProviderLink = `-- name: CreatePracticeProviderLink :one
INSERT INTO practice_provider (practice_id, provider_id, is_main)
VALUES ($1, $2, $3)
RETURNING id
`

type CreatePracticeProviderLinkParams struct {
	PracticeID uuid.UUID
	ProviderID uuid.UUID
	IsMain     bool
}

func (q *Queries) CreatePracticeProviderLink(ctx context.Context, arg CreatePracticeProviderLinkParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPracticeProviderLink, arg.PracticeID, arg.ProviderID, arg.IsMain)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO provider (first_name, last_name, title, specialty)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, first_name, last_name, title, specialty
`

type CreateProviderParams struct {
	FirstName string
	LastName  string
	Title     *string
	Specialty string
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.FirstName,
		arg.LastName,
		arg.Title,
		arg.Specialty,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Title,
		&i.Specialty,
	)
	return i, err
}

const deletePracticeProviderLink = `-- name: DeletePracticeProviderLink :execrows
DELETE FROM practice_provider
WHERE practice_id = $1
  AND provider_id = $2
  AND is_main = FALSE
`

type DeletePracticeProviderLinkParams struct {
	PracticeID uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) DeletePracticeProviderLink(ctx context.Context, arg DeletePracticeProviderLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePracticeProviderLink, arg.PracticeID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProviderForMutation = `-- name: GetProviderForMutation :one
SELECT p.id, p.created_at, p.first_name, p.last_name, p.title, p.specialty,
       pp.is_main
FROM practice_provider pp
JOIN provider p ON p.id = pp.provider_id
WHERE pp.practice_id = $1
  AND pp.provider_id = $2
`

type GetProviderForMutationParams struct {
	PracticeID uuid.UUID
	ProviderID uuid.UUID
}

type GetProviderForMutationRow struct {
	ID        uuid.UUID
	CreatedAt *time.Time
	FirstName string
	LastName  string
	Title     *string
	Specialty string
	IsMain    bool
}

func (q *Queries) GetProviderForMutation(ctx context.Context, arg GetProviderForMutationParams) (GetProviderForMutationRow, error) {
	row := q.db.QueryRow(ctx, getProviderForMutation, arg.PracticeID, arg.ProviderID)
	var i GetProviderForMutationRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Title,
		&i.Specialty,
		&i.IsMain,
	)
	return i, err
}

const getProvidersByPracticeID = `-- name: GetProvidersByPracticeID :many
SELECT p.id, p.created_at, p.first_name, p.last_name, p.title, p.specialty,
       pp.is_main
FROM practice_provider pp
JOIN provider p ON p.id = pp.provider_id
WHERE pp.practice_id = $1
ORDER BY pp.is_main DESC, p.created_at ASC, p.id ASC
`

type GetProvidersByPracticeIDRow struct {
	ID        uuid.UUID
	CreatedAt *time.Time
	FirstName string
	LastName  string
	Title     *string
	Specialty string
	IsMain    bool
}

func (q *Queries) GetProvidersByPracticeID(ctx context.Context, practiceID uuid.UUID) ([]GetProvidersByPracticeIDRow, error) {
	rows, err := q.db.Query(ctx, getProvidersByPracticeID, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProvidersByPracticeIDRow
	for rows.Next() {
		var i GetProvidersByPracticeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Title,
			&i.Specialty,
			&i.IsMain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPracticeForProviderMutation = `-- name: LockPracticeForProviderMutation :one
SELECT id
FROM practices
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPracticeForProviderMutation(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPracticeForProviderMutation, id)
	err := row.Scan(&id)
	return id, err
}

const patchProvider = `-- name: PatchProvider :execrows
UPDATE provider p
SET
    first_name = CASE
        WHEN $1::boolean THEN $2::text
        ELSE p.first_name
    END,
    last_name = CASE
        WHEN $3::boolean THEN $4::text
        ELSE p.last_name
    END,
    title = CASE
        WHEN $5::boolean THEN $6::text
        ELSE p.title
    END,
    specialty = CASE
        WHEN $7::boolean THEN $8::text
        ELSE p.specialty
    END
FROM practice_provider pp
WHERE p.id = $9
  AND pp.provider_id = p.id
  AND pp.practice_id = $10
`

type PatchProviderParams struct {
	SetFirstName bool
	FirstName    string
	SetLastName  bool
	LastName     string
	SetTitle     bool
	Title        *string
	SetSpecialty bool
	Specialty    string
	ProviderID   uuid.UUID
	PracticeID   uuid.UUID
}

func (q *Queries) PatchProvider(ctx context.Context, arg PatchProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, patchProvider,
		arg.SetFirstName,
		arg.FirstName,
		arg.SetLastName,
		arg.LastName,
		arg.SetTitle,
		arg.Title,
		arg.SetSpecialty,
		arg.Specialty,
		arg.ProviderID,
		arg.PracticeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMainProvider = `-- name: SetMainProvider :execrows
UPDATE practice_provider
SET is_main = TRUE
WHERE practice_id = $1
  AND provider_id = $2
`

type SetMainProviderParams struct {
	PracticeID uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) SetMainProvider(ctx context.Context, arg SetMainProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMainProvider, arg.PracticeID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
