// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: public_booking.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicBookingPractice = `-- name: GetPublicBookingPractice :one
SELECT
    p.id, p.name, p.logo, p.city, p.street_address, p.phone, p.email, p.website,
    p.practice_code, p.instagram, p.facebook, p.has_multiple_providers,
    p.practice_category, p.specialty, p.is_active, p.is_suspended,
    ps.multiple_locations_enabled, ps.available_weekdays, ps.theme, ps.theme_colors,
    s.status AS subscription_status, s.plan AS subscription_plan,
    s."trialEnd" AS subscription_trial_end,
    s."periodEnd" AS subscription_period_end,
    s."cancelAt" AS subscription_cancel_at
FROM practices p
JOIN practice_settings ps ON ps.practice_id = p.id
LEFT JOIN subscription s ON s."referenceId" = p.id::text
WHERE p.practice_code = $1
`

type GetPublicBookingPracticeRow struct {
	ID                       uuid.UUID
	Name                     string
	Logo                     *string
	City                     string
	StreetAddress            *string
	Phone                    *string
	Email                    *string
	Website                  *string
	PracticeCode             string
	Instagram                *string
	Facebook                 *string
	HasMultipleProviders     bool
	PracticeCategory         string
	Specialty                *string
	IsActive                 bool
	IsSuspended              bool
	MultipleLocationsEnabled bool
	AvailableWeekdays        []int16
	Theme                    string
	ThemeColors              []byte
	SubscriptionStatus       *string
	SubscriptionPlan         *string
	SubscriptionTrialEnd     pgtype.Timestamptz
	SubscriptionPeriodEnd    pgtype.Timestamptz
	SubscriptionCancelAt     pgtype.Timestamptz
}

func (q *Queries) GetPublicBookingPractice(ctx context.Context, practiceCode string) (GetPublicBookingPracticeRow, error) {
	row := q.db.QueryRow(ctx, getPublicBookingPractice, practiceCode)
	var i GetPublicBookingPracticeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.City,
		&i.StreetAddress,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.PracticeCode,
		&i.Instagram,
		&i.Facebook,
		&i.HasMultipleProviders,
		&i.PracticeCategory,
		&i.Specialty,
		&i.IsActive,
		&i.IsSuspended,
		&i.MultipleLocationsEnabled,
		&i.AvailableWeekdays,
		&i.Theme,
		&i.ThemeColors,
		&i.SubscriptionStatus,
		&i.SubscriptionPlan,
		&i.SubscriptionTrialEnd,
		&i.SubscriptionPeriodEnd,
		&i.SubscriptionCancelAt,
	)
	return i, err
}

const getPublicLocations = `-- name: GetPublicLocations :many
SELECT id, name, sort_order, available_weekdays
FROM practice_locations
WHERE practice_id = $1
  AND is_active = TRUE
  AND deleted_at IS NULL
  AND cardinality(available_weekdays) > 0
ORDER BY sort_order ASC
`

type GetPublicLocationsRow struct {
	ID                uuid.UUID
	Name              string
	SortOrder         int32
	AvailableWeekdays []int16
}

func (q *Queries) GetPublicLocations(ctx context.Context, practiceID uuid.UUID) ([]GetPublicLocationsRow, error) {
	rows, err := q.db.Query(ctx, getPublicLocations, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicLocationsRow
	for rows.Next() {
		var i GetPublicLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.AvailableWeekdays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicProcedureTypes = `-- name: GetPublicProcedureTypes :many
SELECT id, name, value, sort_order, is_primary
FROM procedure_types
WHERE practice_id = $1
  AND is_active = TRUE
  AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type GetPublicProcedureTypesRow struct {
	ID        uuid.UUID
	Name      string
	Value     string
	SortOrder int32
	IsPrimary bool
}

func (q *Queries) GetPublicProcedureTypes(ctx context.Context, practiceID uuid.UUID) ([]GetPublicProcedureTypesRow, error) {
	rows, err := q.db.Query(ctx, getPublicProcedureTypes, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicProcedureTypesRow
	for rows.Next() {
		var i GetPublicProcedureTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.SortOrder,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicProviders = `-- name: GetPublicProviders :many
SELECT p.id, p.first_name, p.last_name, p.title, p.specialty
FROM practice_provider pp
JOIN provider p ON p.id = pp.provider_id
WHERE pp.practice_id = $1
ORDER BY pp.is_main DESC, p.created_at ASC, p.id ASC
`

type GetPublicProvidersRow struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Title     *string
	Specialty string
}

func (q *Queries) GetPublicProviders(ctx context.Context, practiceID uuid.UUID) ([]GetPublicProvidersRow, error) {
	rows, err := q.db.Query(ctx, getPublicProviders, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicProvidersRow
	for rows.Next() {
		var i GetPublicProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Title,
			&i.Specialty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
