// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: registrations.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPatientRegistration = `-- name: CreatePatientRegistration :one
INSERT INTO patient_registrations (
    practice_id, appointment_id, patient_name, patient_email, patient_phone,
    token, token_expires_at, status, sent_by_user_id, sent_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, 'pending', $8, NULL
)
RETURNING id, token, token_expires_at, status
`

type CreatePatientRegistrationParams struct {
	PracticeID     uuid.UUID
	AppointmentID  *uuid.UUID
	PatientName    string
	PatientEmail   *string
	PatientPhone   *string
	Token          string
	TokenExpiresAt time.Time
	SentByUserID   uuid.UUID
}

type CreatePatientRegistrationRow struct {
	ID             uuid.UUID
	Token          string
	TokenExpiresAt time.Time
	Status         string
}

func (q *Queries) CreatePatientRegistration(ctx context.Context, arg CreatePatientRegistrationParams) (CreatePatientRegistrationRow, error) {
	row := q.db.QueryRow(ctx, createPatientRegistration,
		arg.PracticeID,
		arg.AppointmentID,
		arg.PatientName,
		arg.PatientEmail,
		arg.PatientPhone,
		arg.Token,
		arg.TokenExpiresAt,
		arg.SentByUserID,
	)
	var i CreatePatientRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.TokenExpiresAt,
		&i.Status,
	)
	return i, err
}

const getRegistrationAppointment = `-- name: GetRegistrationAppointment :one
SELECT id, first_name, email, mobile_phone
FROM appointments
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
`

type GetRegistrationAppointmentParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

type GetRegistrationAppointmentRow struct {
	ID          uuid.UUID
	FirstName   string
	Email       string
	MobilePhone string
}

func (q *Queries) GetRegistrationAppointment(ctx context.Context, arg GetRegistrationAppointmentParams) (GetRegistrationAppointmentRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationAppointment, arg.ID, arg.PracticeID)
	var i GetRegistrationAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.Email,
		&i.MobilePhone,
	)
	return i, err
}

const getRegistrationDeleteState = `-- name: GetRegistrationDeleteState :one
SELECT status
FROM patient_registrations
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
`

type GetRegistrationDeleteStateParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) GetRegistrationDeleteState(ctx context.Context, arg GetRegistrationDeleteStateParams) (string, error) {
	row := q.db.QueryRow(ctx, getRegistrationDeleteState, arg.ID, arg.PracticeID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getRegistrationDetail = `-- name: GetRegistrationDetail :one
SELECT r.id, r.patient_name, r.patient_email, r.patient_phone, r.status,
       r.sent_at, r.completed_at, r.appointment_id, r.created_at,
       d.form_data, d.form_version
FROM patient_registrations r
LEFT JOIN patient_registration_data d ON d.registration_id = r.id
WHERE r.id = $1
  AND r.practice_id = $2
  AND r.deleted_at IS NULL
`

type GetRegistrationDetailParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

type GetRegistrationDetailRow struct {
	ID            uuid.UUID
	PatientName   string
	PatientEmail  *string
	PatientPhone  *string
	Status        string
	SentAt        *time.Time
	CompletedAt   *time.Time
	AppointmentID *uuid.UUID
	CreatedAt     time.Time
	FormData      []byte
	FormVersion   *string
}

func (q *Queries) GetRegistrationDetail(ctx context.Context, arg GetRegistrationDetailParams) (GetRegistrationDetailRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationDetail, arg.ID, arg.PracticeID)
	var i GetRegistrationDetailRow
	err := row.Scan(
		&i.ID,
		&i.PatientName,
		&i.PatientEmail,
		&i.PatientPhone,
		&i.Status,
		&i.SentAt,
		&i.CompletedAt,
		&i.AppointmentID,
		&i.CreatedAt,
		&i.FormData,
		&i.FormVersion,
	)
	return i, err
}

const getRegistrationDuplicate = `-- name: GetRegistrationDuplicate :one
SELECT id
FROM patient_registrations
WHERE practice_id = $1
  AND patient_name = $2
  AND (
    ($3::text IS NOT NULL AND patient_email = $3::text)
    OR ($4::text IS NOT NULL AND patient_phone = $4::text)
  )
LIMIT 1
`

type GetRegistrationDuplicateParams struct {
	PracticeID   uuid.UUID
	PatientName  string
	PatientEmail *string
	PatientPhone *string
}

func (q *Queries) GetRegistrationDuplicate(ctx context.Context, arg GetRegistrationDuplicateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRegistrationDuplicate,
		arg.PracticeID,
		arg.PatientName,
		arg.PatientEmail,
		arg.PatientPhone,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRegistrationForLink = `-- name: GetRegistrationForLink :one
SELECT id, patient_name, patient_email, patient_phone, status, token,
       token_expires_at, sent_at
FROM patient_registrations
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
`

type GetRegistrationForLinkParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

type GetRegistrationForLinkRow struct {
	ID             uuid.UUID
	PatientName    string
	PatientEmail   *string
	PatientPhone   *string
	Status         string
	Token          string
	TokenExpiresAt time.Time
	SentAt         *time.Time
}

func (q *Queries) GetRegistrationForLink(ctx context.Context, arg GetRegistrationForLinkParams) (GetRegistrationForLinkRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationForLink, arg.ID, arg.PracticeID)
	var i GetRegistrationForLinkRow
	err := row.Scan(
		&i.ID,
		&i.PatientName,
		&i.PatientEmail,
		&i.PatientPhone,
		&i.Status,
		&i.Token,
		&i.TokenExpiresAt,
		&i.SentAt,
	)
	return i, err
}

const listRegistrations = `-- name: ListRegistrations :many
SELECT id, patient_name, patient_email, patient_phone, status, sent_at,
       completed_at, appointment_id, created_at, token
FROM patient_registrations
WHERE practice_id = $1
  AND deleted_at IS NULL
  AND ($2::text = '' OR patient_name ILIKE '%' || $2::text || '%')
  AND ($3::uuid IS NULL OR appointment_id = $3::uuid)
ORDER BY created_at DESC, id DESC
`

type ListRegistrationsParams struct {
	PracticeID    uuid.UUID
	Search        string
	AppointmentID *uuid.UUID
}

type ListRegistrationsRow struct {
	ID            uuid.UUID
	PatientName   string
	PatientEmail  *string
	PatientPhone  *string
	Status        string
	SentAt        *time.Time
	CompletedAt   *time.Time
	AppointmentID *uuid.UUID
	CreatedAt     time.Time
	Token         string
}

func (q *Queries) ListRegistrations(ctx context.Context, arg ListRegistrationsParams) ([]ListRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listRegistrations, arg.PracticeID, arg.Search, arg.AppointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationsRow
	for rows.Next() {
		var i ListRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientName,
			&i.PatientEmail,
			&i.PatientPhone,
			&i.Status,
			&i.SentAt,
			&i.CompletedAt,
			&i.AppointmentID,
			&i.CreatedAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRegistrationSent = `-- name: MarkRegistrationSent :execrows
UPDATE patient_registrations
SET sent_at = NOW()
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
  AND status <> 'completed'
`

type MarkRegistrationSentParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) MarkRegistrationSent(ctx context.Context, arg MarkRegistrationSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRegistrationSent, arg.ID, arg.PracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRegistrationToken = `-- name: RotateRegistrationToken :one
UPDATE patient_registrations
SET token = $1, token_expires_at = $2,
    status = 'pending'
WHERE id = $3
  AND practice_id = $4
  AND deleted_at IS NULL
  AND status <> 'completed'
RETURNING token, token_expires_at, status
`

type RotateRegistrationTokenParams struct {
	Token          string
	TokenExpiresAt time.Time
	ID             uuid.UUID
	PracticeID     uuid.UUID
}

type RotateRegistrationTokenRow struct {
	Token          string
	TokenExpiresAt time.Time
	Status         string
}

func (q *Queries) RotateRegistrationToken(ctx context.Context, arg RotateRegistrationTokenParams) (RotateRegistrationTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateRegistrationToken,
		arg.Token,
		arg.TokenExpiresAt,
		arg.ID,
		arg.PracticeID,
	)
	var i RotateRegistrationTokenRow
	err := row.Scan(&i.Token, &i.TokenExpiresAt, &i.Status)
	return i, err
}

const softDeleteRegistration = `-- name: SoftDeleteRegistration :one
UPDATE patient_registrations
SET deleted_at = NOW()
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
  AND status <> 'completed'
RETURNING id
`

type SoftDeleteRegistrationParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) SoftDeleteRegistration(ctx context.Context, arg SoftDeleteRegistrationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteRegistration, arg.ID, arg.PracticeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
