// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: registrations.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completePatientRegistration = `-- name: CompletePatientRegistration :execrows
UPDATE patient_registrations
SET patient_id = $1, status = 'completed', completed_at = NOW()
WHERE id = $2
  AND status <> 'completed'
  AND deleted_at IS NULL
`

type CompletePatientRegistrationParams struct {
	PatientID *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) CompletePatientRegistration(ctx context.Context, arg CompletePatientRegistrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completePatientRegistration, arg.PatientID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPatientRegistration = `-- name: CreatePatientRegistration :one
INSERT INTO patient_registrations (
    practice_id, appointment_id, patient_name, patient_email, patient_phone,
    token, token_expires_at, status, sent_by_user_id, sent_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, 'pending', $8, NULL
)
RETURNING id, token, token_expires_at, status
`

type CreatePatientRegistrationParams struct {
	PracticeID     uuid.UUID
	AppointmentID  *uuid.UUID
	PatientName    string
	PatientEmail   *string
	PatientPhone   *string
	Token          string
	TokenExpiresAt time.Time
	SentByUserID   uuid.UUID
}

type CreatePatientRegistrationRow struct {
	ID             uuid.UUID
	Token          string
	TokenExpiresAt time.Time
	Status         string
}

func (q *Queries) CreatePatientRegistration(ctx context.Context, arg CreatePatientRegistrationParams) (CreatePatientRegistrationRow, error) {
	row := q.db.QueryRow(ctx, createPatientRegistration,
		arg.PracticeID,
		arg.AppointmentID,
		arg.PatientName,
		arg.PatientEmail,
		arg.PatientPhone,
		arg.Token,
		arg.TokenExpiresAt,
		arg.SentByUserID,
	)
	var i CreatePatientRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.TokenExpiresAt,
		&i.Status,
	)
	return i, err
}

const createRegistrationPatient = `-- name: CreateRegistrationPatient :one
INSERT INTO patients (
    practice_id, first_name, last_name, email, mobile_phone
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING id
`

type CreateRegistrationPatientParams struct {
	PracticeID  uuid.UUID
	FirstName   string
	LastName    string
	Email       *string
	MobilePhone *string
}

func (q *Queries) CreateRegistrationPatient(ctx context.Context, arg CreateRegistrationPatientParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRegistrationPatient,
		arg.PracticeID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const enrichRegistrationPatient = `-- name: EnrichRegistrationPatient :execrows
UPDATE patients
SET home_phone = $1,
    date_of_birth = $2,
    address_line_1 = $3,
    address_line_2 = $4,
    city = $5,
    email_consent = $6,
    emergency_contact_name = $7,
    emergency_contact_phone = $8,
    updated_at = NOW()
WHERE id = $9
  AND practice_id = $10
`

type EnrichRegistrationPatientParams struct {
	HomePhone             *string
	DateOfBirth           *time.Time
	AddressLine1          *string
	AddressLine2          *string
	City                  *string
	EmailConsent          bool
	EmergencyContactName  *string
	EmergencyContactPhone *string
	ID                    uuid.UUID
	PracticeID            uuid.UUID
}

func (q *Queries) EnrichRegistrationPatient(ctx context.Context, arg EnrichRegistrationPatientParams) (int64, error) {
	result, err := q.db.Exec(ctx, enrichRegistrationPatient,
		arg.HomePhone,
		arg.DateOfBirth,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.EmailConsent,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.ID,
		arg.PracticeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findRegistrationPatientByEmail = `-- name: FindRegistrationPatientByEmail :one
SELECT id FROM patients
WHERE practice_id = $1
  AND email = $2
  AND first_name ILIKE $3
  AND last_name ILIKE $4
LIMIT 1
`

type FindRegistrationPatientByEmailParams struct {
	PracticeID uuid.UUID
	Email      *string
	FirstName  string
	LastName   string
}

func (q *Queries) FindRegistrationPatientByEmail(ctx context.Context, arg FindRegistrationPatientByEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findRegistrationPatientByEmail,
		arg.PracticeID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findRegistrationPatientByPhone = `-- name: FindRegistrationPatientByPhone :one
SELECT id FROM patients
WHERE practice_id = $1
  AND mobile_phone = $2
  AND first_name ILIKE $3
  AND last_name ILIKE $4
LIMIT 1
`

type FindRegistrationPatientByPhoneParams struct {
	PracticeID  uuid.UUID
	MobilePhone *string
	FirstName   string
	LastName    string
}

func (q *Queries) FindRegistrationPatientByPhone(ctx context.Context, arg FindRegistrationPatientByPhoneParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findRegistrationPatientByPhone,
		arg.PracticeID,
		arg.MobilePhone,
		arg.FirstName,
		arg.LastName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPublicRegistrationBootstrap = `-- name: GetPublicRegistrationBootstrap :one
SELECT
    r.id, r.practice_id, r.appointment_id, r.status, r.token_expires_at,
    p.name AS practice_name, p.logo AS practice_logo,
    p.practice_category, p.is_active, p.is_suspended,
    ps.dental_history_enabled, ps.tmj_history_enabled,
    ps.physiotherapy_history_enabled, ps.optometry_history_enabled,
    ps.custom_form_sections, ps.theme, ps.theme_colors,
    a.first_name, a.last_name, a.email, a.mobile_phone,
    s.status AS subscription_status, s.plan AS subscription_plan,
    s."trialEnd" AS subscription_trial_end,
    s."periodEnd" AS subscription_period_end,
    s."cancelAt" AS subscription_cancel_at
FROM patient_registrations r
JOIN practices p ON p.id = r.practice_id
LEFT JOIN practice_settings ps ON ps.practice_id = r.practice_id
LEFT JOIN appointments a
  ON a.id = r.appointment_id AND a.practice_id = r.practice_id AND a.deleted_at IS NULL
LEFT JOIN subscription s ON s."referenceId" = r.practice_id::text
WHERE r.token = $1
  AND r.deleted_at IS NULL
`

type GetPublicRegistrationBootstrapRow struct {
	ID                          uuid.UUID
	PracticeID                  uuid.UUID
	AppointmentID               *uuid.UUID
	Status                      string
	TokenExpiresAt              time.Time
	PracticeName                string
	PracticeLogo                *string
	PracticeCategory            string
	IsActive                    bool
	IsSuspended                 bool
	DentalHistoryEnabled        *bool
	TmjHistoryEnabled           *bool
	PhysiotherapyHistoryEnabled *bool
	OptometryHistoryEnabled     *bool
	CustomFormSections          []byte
	Theme                       *string
	ThemeColors                 []byte
	FirstName                   *string
	LastName                    *string
	Email                       *string
	MobilePhone                 *string
	SubscriptionStatus          *string
	SubscriptionPlan            *string
	SubscriptionTrialEnd        pgtype.Timestamptz
	SubscriptionPeriodEnd       pgtype.Timestamptz
	SubscriptionCancelAt        pgtype.Timestamptz
}

func (q *Queries) GetPublicRegistrationBootstrap(ctx context.Context, token string) (GetPublicRegistrationBootstrapRow, error) {
	row := q.db.QueryRow(ctx, getPublicRegistrationBootstrap, token)
	var i GetPublicRegistrationBootstrapRow
	err := row.Scan(
		&i.ID,
		&i.PracticeID,
		&i.AppointmentID,
		&i.Status,
		&i.TokenExpiresAt,
		&i.PracticeName,
		&i.PracticeLogo,
		&i.PracticeCategory,
		&i.IsActive,
		&i.IsSuspended,
		&i.DentalHistoryEnabled,
		&i.TmjHistoryEnabled,
		&i.PhysiotherapyHistoryEnabled,
		&i.OptometryHistoryEnabled,
		&i.CustomFormSections,
		&i.Theme,
		&i.ThemeColors,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.SubscriptionStatus,
		&i.SubscriptionPlan,
		&i.SubscriptionTrialEnd,
		&i.SubscriptionPeriodEnd,
		&i.SubscriptionCancelAt,
	)
	return i, err
}

const getRegistrationAppointment = `-- name: GetRegistrationAppointment :one
SELECT id, first_name, email, mobile_phone
FROM appointments
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
`

type GetRegistrationAppointmentParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

type GetRegistrationAppointmentRow struct {
	ID          uuid.UUID
	FirstName   string
	Email       string
	MobilePhone string
}

func (q *Queries) GetRegistrationAppointment(ctx context.Context, arg GetRegistrationAppointmentParams) (GetRegistrationAppointmentRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationAppointment, arg.ID, arg.PracticeID)
	var i GetRegistrationAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.Email,
		&i.MobilePhone,
	)
	return i, err
}

const getRegistrationDeleteState = `-- name: GetRegistrationDeleteState :one
SELECT status
FROM patient_registrations
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
`

type GetRegistrationDeleteStateParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) GetRegistrationDeleteState(ctx context.Context, arg GetRegistrationDeleteStateParams) (string, error) {
	row := q.db.QueryRow(ctx, getRegistrationDeleteState, arg.ID, arg.PracticeID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getRegistrationDetail = `-- name: GetRegistrationDetail :one
SELECT r.id, r.patient_name, r.patient_email, r.patient_phone, r.status,
       r.sent_at, r.completed_at, r.appointment_id, r.created_at,
       d.form_data, d.form_version
FROM patient_registrations r
LEFT JOIN patient_registration_data d ON d.registration_id = r.id
WHERE r.id = $1
  AND r.practice_id = $2
  AND r.deleted_at IS NULL
`

type GetRegistrationDetailParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

type GetRegistrationDetailRow struct {
	ID            uuid.UUID
	PatientName   string
	PatientEmail  *string
	PatientPhone  *string
	Status        string
	SentAt        *time.Time
	CompletedAt   *time.Time
	AppointmentID *uuid.UUID
	CreatedAt     time.Time
	FormData      []byte
	FormVersion   *string
}

func (q *Queries) GetRegistrationDetail(ctx context.Context, arg GetRegistrationDetailParams) (GetRegistrationDetailRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationDetail, arg.ID, arg.PracticeID)
	var i GetRegistrationDetailRow
	err := row.Scan(
		&i.ID,
		&i.PatientName,
		&i.PatientEmail,
		&i.PatientPhone,
		&i.Status,
		&i.SentAt,
		&i.CompletedAt,
		&i.AppointmentID,
		&i.CreatedAt,
		&i.FormData,
		&i.FormVersion,
	)
	return i, err
}

const getRegistrationDuplicate = `-- name: GetRegistrationDuplicate :one
SELECT id
FROM patient_registrations
WHERE practice_id = $1
  AND patient_name = $2
  AND (
    ($3::text IS NOT NULL AND patient_email = $3::text)
    OR ($4::text IS NOT NULL AND patient_phone = $4::text)
  )
LIMIT 1
`

type GetRegistrationDuplicateParams struct {
	PracticeID   uuid.UUID
	PatientName  string
	PatientEmail *string
	PatientPhone *string
}

func (q *Queries) GetRegistrationDuplicate(ctx context.Context, arg GetRegistrationDuplicateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRegistrationDuplicate,
		arg.PracticeID,
		arg.PatientName,
		arg.PatientEmail,
		arg.PatientPhone,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRegistrationForLink = `-- name: GetRegistrationForLink :one
SELECT id, patient_name, patient_email, patient_phone, status, token,
       token_expires_at, sent_at, appointment_id
FROM patient_registrations
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
`

type GetRegistrationForLinkParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

type GetRegistrationForLinkRow struct {
	ID             uuid.UUID
	PatientName    string
	PatientEmail   *string
	PatientPhone   *string
	Status         string
	Token          string
	TokenExpiresAt time.Time
	SentAt         *time.Time
	AppointmentID  *uuid.UUID
}

func (q *Queries) GetRegistrationForLink(ctx context.Context, arg GetRegistrationForLinkParams) (GetRegistrationForLinkRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationForLink, arg.ID, arg.PracticeID)
	var i GetRegistrationForLinkRow
	err := row.Scan(
		&i.ID,
		&i.PatientName,
		&i.PatientEmail,
		&i.PatientPhone,
		&i.Status,
		&i.Token,
		&i.TokenExpiresAt,
		&i.SentAt,
		&i.AppointmentID,
	)
	return i, err
}

const insertPatientRegistrationData = `-- name: InsertPatientRegistrationData :exec
INSERT INTO patient_registration_data (registration_id, form_version, form_data)
VALUES ($1, $2, $3)
`

type InsertPatientRegistrationDataParams struct {
	RegistrationID uuid.UUID
	FormVersion    string
	FormData       []byte
}

func (q *Queries) InsertPatientRegistrationData(ctx context.Context, arg InsertPatientRegistrationDataParams) error {
	_, err := q.db.Exec(ctx, insertPatientRegistrationData, arg.RegistrationID, arg.FormVersion, arg.FormData)
	return err
}

const listRegistrations = `-- name: ListRegistrations :many
SELECT id, patient_name, patient_email, patient_phone, status, sent_at,
       completed_at, appointment_id, created_at, token
FROM patient_registrations
WHERE practice_id = $1
  AND deleted_at IS NULL
  AND ($2::text = '' OR patient_name ILIKE '%' || $2::text || '%')
  AND ($3::uuid IS NULL OR appointment_id = $3::uuid)
ORDER BY created_at DESC, id DESC
`

type ListRegistrationsParams struct {
	PracticeID    uuid.UUID
	Search        string
	AppointmentID *uuid.UUID
}

type ListRegistrationsRow struct {
	ID            uuid.UUID
	PatientName   string
	PatientEmail  *string
	PatientPhone  *string
	Status        string
	SentAt        *time.Time
	CompletedAt   *time.Time
	AppointmentID *uuid.UUID
	CreatedAt     time.Time
	Token         string
}

func (q *Queries) ListRegistrations(ctx context.Context, arg ListRegistrationsParams) ([]ListRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listRegistrations, arg.PracticeID, arg.Search, arg.AppointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationsRow
	for rows.Next() {
		var i ListRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientName,
			&i.PatientEmail,
			&i.PatientPhone,
			&i.Status,
			&i.SentAt,
			&i.CompletedAt,
			&i.AppointmentID,
			&i.CreatedAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPublicRegistration = `-- name: LockPublicRegistration :one
SELECT r.id, r.practice_id, r.status, r.token_expires_at,
       p.is_active, p.is_suspended,
       s.status AS subscription_status, s.plan AS subscription_plan,
       s."trialEnd" AS subscription_trial_end,
       s."periodEnd" AS subscription_period_end,
       s."cancelAt" AS subscription_cancel_at
FROM patient_registrations r
JOIN practices p ON p.id = r.practice_id
LEFT JOIN subscription s ON s."referenceId" = r.practice_id::text
WHERE r.token = $1
  AND r.deleted_at IS NULL
FOR UPDATE OF r
`

type LockPublicRegistrationRow struct {
	ID                    uuid.UUID
	PracticeID            uuid.UUID
	Status                string
	TokenExpiresAt        time.Time
	IsActive              bool
	IsSuspended           bool
	SubscriptionStatus    *string
	SubscriptionPlan      *string
	SubscriptionTrialEnd  pgtype.Timestamptz
	SubscriptionPeriodEnd pgtype.Timestamptz
	SubscriptionCancelAt  pgtype.Timestamptz
}

func (q *Queries) LockPublicRegistration(ctx context.Context, token string) (LockPublicRegistrationRow, error) {
	row := q.db.QueryRow(ctx, lockPublicRegistration, token)
	var i LockPublicRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.PracticeID,
		&i.Status,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.IsSuspended,
		&i.SubscriptionStatus,
		&i.SubscriptionPlan,
		&i.SubscriptionTrialEnd,
		&i.SubscriptionPeriodEnd,
		&i.SubscriptionCancelAt,
	)
	return i, err
}

const markRegistrationExpired = `-- name: MarkRegistrationExpired :execrows
UPDATE patient_registrations
SET status = 'expired'
WHERE id = $1
  AND deleted_at IS NULL
  AND status <> 'completed'
`

func (q *Queries) MarkRegistrationExpired(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markRegistrationExpired, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRegistrationSent = `-- name: MarkRegistrationSent :execrows
UPDATE patient_registrations
SET sent_at = NOW()
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
  AND status <> 'completed'
`

type MarkRegistrationSentParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) MarkRegistrationSent(ctx context.Context, arg MarkRegistrationSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRegistrationSent, arg.ID, arg.PracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreRegistrationEmail = `-- name: RestoreRegistrationEmail :execrows
UPDATE patient_registrations
SET patient_email = $1
WHERE id = $2
  AND practice_id = $3
  AND patient_email = $4
`

type RestoreRegistrationEmailParams struct {
	PreviousEmail *string
	ID            uuid.UUID
	PracticeID    uuid.UUID
	ExpectedEmail *string
}

func (q *Queries) RestoreRegistrationEmail(ctx context.Context, arg RestoreRegistrationEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreRegistrationEmail,
		arg.PreviousEmail,
		arg.ID,
		arg.PracticeID,
		arg.ExpectedEmail,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreRegistrationPhone = `-- name: RestoreRegistrationPhone :execrows
UPDATE patient_registrations
SET patient_phone = $1
WHERE id = $2
  AND practice_id = $3
  AND patient_phone = $4
`

type RestoreRegistrationPhoneParams struct {
	PreviousPhone *string
	ID            uuid.UUID
	PracticeID    uuid.UUID
	ExpectedPhone *string
}

func (q *Queries) RestoreRegistrationPhone(ctx context.Context, arg RestoreRegistrationPhoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreRegistrationPhone,
		arg.PreviousPhone,
		arg.ID,
		arg.PracticeID,
		arg.ExpectedPhone,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreRegistrationToken = `-- name: RestoreRegistrationToken :execrows
UPDATE patient_registrations
SET token = $1,
    token_expires_at = $2,
    status = $3,
    sent_at = $4
WHERE id = $5
  AND practice_id = $6
  AND token = $7
`

type RestoreRegistrationTokenParams struct {
	PreviousToken          string
	PreviousTokenExpiresAt time.Time
	PreviousStatus         string
	PreviousSentAt         *time.Time
	ID                     uuid.UUID
	PracticeID             uuid.UUID
	ExpectedToken          string
}

func (q *Queries) RestoreRegistrationToken(ctx context.Context, arg RestoreRegistrationTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreRegistrationToken,
		arg.PreviousToken,
		arg.PreviousTokenExpiresAt,
		arg.PreviousStatus,
		arg.PreviousSentAt,
		arg.ID,
		arg.PracticeID,
		arg.ExpectedToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRegistrationToken = `-- name: RotateRegistrationToken :one
UPDATE patient_registrations
SET token = $1, token_expires_at = $2,
    status = 'pending'
WHERE id = $3
  AND practice_id = $4
  AND deleted_at IS NULL
  AND status <> 'completed'
RETURNING token, token_expires_at, status
`

type RotateRegistrationTokenParams struct {
	Token          string
	TokenExpiresAt time.Time
	ID             uuid.UUID
	PracticeID     uuid.UUID
}

type RotateRegistrationTokenRow struct {
	Token          string
	TokenExpiresAt time.Time
	Status         string
}

func (q *Queries) RotateRegistrationToken(ctx context.Context, arg RotateRegistrationTokenParams) (RotateRegistrationTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateRegistrationToken,
		arg.Token,
		arg.TokenExpiresAt,
		arg.ID,
		arg.PracticeID,
	)
	var i RotateRegistrationTokenRow
	err := row.Scan(&i.Token, &i.TokenExpiresAt, &i.Status)
	return i, err
}

const softDeleteRegistration = `-- name: SoftDeleteRegistration :one
UPDATE patient_registrations
SET deleted_at = NOW()
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
  AND status <> 'completed'
RETURNING id
`

type SoftDeleteRegistrationParams struct {
	ID         uuid.UUID
	PracticeID uuid.UUID
}

func (q *Queries) SoftDeleteRegistration(ctx context.Context, arg SoftDeleteRegistrationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteRegistration, arg.ID, arg.PracticeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateRegistrationEmail = `-- name: UpdateRegistrationEmail :execrows
UPDATE patient_registrations
SET patient_email = $1
WHERE id = $2
  AND practice_id = $3
  AND deleted_at IS NULL
  AND status <> 'completed'
`

type UpdateRegistrationEmailParams struct {
	PatientEmail *string
	ID           uuid.UUID
	PracticeID   uuid.UUID
}

func (q *Queries) UpdateRegistrationEmail(ctx context.Context, arg UpdateRegistrationEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRegistrationEmail, arg.PatientEmail, arg.ID, arg.PracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRegistrationPhone = `-- name: UpdateRegistrationPhone :execrows
UPDATE patient_registrations
SET patient_phone = $1
WHERE id = $2
  AND practice_id = $3
  AND deleted_at IS NULL
  AND status <> 'completed'
`

type UpdateRegistrationPhoneParams struct {
	PatientPhone *string
	ID           uuid.UUID
	PracticeID   uuid.UUID
}

func (q *Queries) UpdateRegistrationPhone(ctx context.Context, arg UpdateRegistrationPhoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRegistrationPhone, arg.PatientPhone, arg.ID, arg.PracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
