// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subscriptions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscription (
    "referenceId",
    plan,
    status,
    "trialStart",
    "trialEnd"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateSubscriptionParams struct {
	ReferenceID string
	Plan        string
	Status      string
	TrialStart  pgtype.Timestamptz
	TrialEnd    pgtype.Timestamptz
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription,
		arg.ReferenceID,
		arg.Plan,
		arg.Status,
		arg.TrialStart,
		arg.TrialEnd,
	)
	return err
}
