// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: team.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPracticeSeatUsage = `-- name: GetPracticeSeatUsage :one
SELECT
  (SELECT COUNT(*) FROM users u
   WHERE u.practice_id = $1 AND u.deleted_at IS NULL AND u.is_active = TRUE)
  +
  (SELECT COUNT(*) FROM practice_invites i
   WHERE i.practice_id = $1 AND i.accepted_at IS NULL AND i.token_expires_at > NOW())
  AS used,
  COALESCE((SELECT plan FROM subscription WHERE "referenceId" = $1::text LIMIT 1), 'pro')::text AS plan
`

type GetPracticeSeatUsageRow struct {
	Used int32
	Plan string
}

func (q *Queries) GetPracticeSeatUsage(ctx context.Context, practiceID *uuid.UUID) (GetPracticeSeatUsageRow, error) {
	row := q.db.QueryRow(ctx, getPracticeSeatUsage, practiceID)
	var i GetPracticeSeatUsageRow
	err := row.Scan(&i.Used, &i.Plan)
	return i, err
}

const getPracticeUserMutationState = `-- name: GetPracticeUserMutationState :one
SELECT id, role, is_active
FROM users
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
`

type GetPracticeUserMutationStateParams struct {
	ID         uuid.UUID
	PracticeID *uuid.UUID
}

type GetPracticeUserMutationStateRow struct {
	ID       uuid.UUID
	Role     *string
	IsActive bool
}

func (q *Queries) GetPracticeUserMutationState(ctx context.Context, arg GetPracticeUserMutationStateParams) (GetPracticeUserMutationStateRow, error) {
	row := q.db.QueryRow(ctx, getPracticeUserMutationState, arg.ID, arg.PracticeID)
	var i GetPracticeUserMutationStateRow
	err := row.Scan(&i.ID, &i.Role, &i.IsActive)
	return i, err
}

const listPracticeUsers = `-- name: ListPracticeUsers :many
SELECT id, first_name, last_name, email, role, org_role, is_active, created_at
FROM users
WHERE practice_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
`

type ListPracticeUsersRow struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     *string
	Role      *string
	OrgRole   *string
	IsActive  bool
	CreatedAt *time.Time
}

func (q *Queries) ListPracticeUsers(ctx context.Context, practiceID *uuid.UUID) ([]ListPracticeUsersRow, error) {
	rows, err := q.db.Query(ctx, listPracticeUsers, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPracticeUsersRow
	for rows.Next() {
		var i ListPracticeUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.OrgRole,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchPracticeUser = `-- name: PatchPracticeUser :execrows
UPDATE users
SET role = CASE WHEN $1::boolean THEN $2::text ELSE role END,
    is_active = CASE WHEN $3::boolean THEN $4::boolean ELSE is_active END
WHERE id = $5
  AND practice_id = $6
  AND deleted_at IS NULL
  AND role <> 'owner'
`

type PatchPracticeUserParams struct {
	SetRole     bool
	Role        string
	SetIsActive bool
	IsActive    bool
	ID          uuid.UUID
	PracticeID  *uuid.UUID
}

func (q *Queries) PatchPracticeUser(ctx context.Context, arg PatchPracticeUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, patchPracticeUser,
		arg.SetRole,
		arg.Role,
		arg.SetIsActive,
		arg.IsActive,
		arg.ID,
		arg.PracticeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePracticeUser = `-- name: SoftDeletePracticeUser :execrows
UPDATE users
SET is_active = FALSE, deleted_at = NOW()
WHERE id = $1
  AND practice_id = $2
  AND deleted_at IS NULL
  AND role <> 'owner'
`

type SoftDeletePracticeUserParams struct {
	ID         uuid.UUID
	PracticeID *uuid.UUID
}

func (q *Queries) SoftDeletePracticeUser(ctx context.Context, arg SoftDeletePracticeUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePracticeUser, arg.ID, arg.PracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
