// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    first_name,
    last_name,
    email,
    mobile_phone,
    role,
    terms_agreed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at
`

type CreateUserParams struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         *string
	MobilePhone   *string
	Role          *string
	TermsAgreedAt *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
		arg.Role,
		arg.TermsAgreedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FirstName,
			&i.LastName,
			&i.MobilePhone,
			&i.Email,
			&i.PracticeID,
			&i.Role,
			&i.OrgRole,
			&i.IsActive,
			&i.InvitedBy,
			&i.AvatarUrl,
			&i.WhatsappNotificationsEnabled,
			&i.TermsAgreedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    email = COALESCE($3, email),
    mobile_phone = COALESCE($4, mobile_phone),
    role = COALESCE($5, role),
    org_role = COALESCE($6, org_role),
    is_active = COALESCE($7, is_active),
    avatar_url = COALESCE($8, avatar_url),
    whatsapp_notifications_enabled = COALESCE($9, whatsapp_notifications_enabled),
    terms_agreed_at = COALESCE($10, terms_agreed_at),
    modified_at = NOW()
WHERE id = $11
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at
`

type UpdateUserParams struct {
	FirstName                    *string
	LastName                     *string
	Email                        *string
	MobilePhone                  *string
	Role                         *string
	OrgRole                      *string
	IsActive                     *bool
	AvatarUrl                    *string
	WhatsappNotificationsEnabled *bool
	TermsAgreedAt                *time.Time
	ID                           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
		arg.Role,
		arg.OrgRole,
		arg.IsActive,
		arg.AvatarUrl,
		arg.WhatsappNotificationsEnabled,
		arg.TermsAgreedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPracticeID = `-- name: UpdateUserPracticeID :one
UPDATE users
SET practice_id = $1
WHERE id = $2
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at
`

type UpdateUserPracticeIDParams struct {
	PracticeID *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateUserPracticeID(ctx context.Context, arg UpdateUserPracticeIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPracticeID, arg.PracticeID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}
