// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    first_name,
    last_name,
    email,
    mobile_phone,
    role,
    terms_agreed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at
`

type CreateUserParams struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         *string
	MobilePhone   *string
	Role          *string
	TermsAgreedAt *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
		arg.Role,
		arg.TermsAgreedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, first_name, last_name, mobile_phone, email, practice_id, role,
       avatar_url, whatsapp_notifications_enabled
FROM users
WHERE id = $1
`

type GetAccountRow struct {
	ID                           uuid.UUID
	FirstName                    string
	LastName                     string
	MobilePhone                  *string
	Email                        *string
	PracticeID                   *uuid.UUID
	Role                         *string
	AvatarUrl                    *string
	WhatsappNotificationsEnabled bool
}

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FirstName,
			&i.LastName,
			&i.MobilePhone,
			&i.Email,
			&i.PracticeID,
			&i.Role,
			&i.OrgRole,
			&i.IsActive,
			&i.InvitedBy,
			&i.AvatarUrl,
			&i.WhatsappNotificationsEnabled,
			&i.TermsAgreedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentUserContext = `-- name: GetCurrentUserContext :one
SELECT
    u.id,
    u.email,
    u.first_name,
    u.last_name,
    u.avatar_url,
    u.practice_id,
    u.role,
    u.is_active,
    u.deleted_at,
    p.id AS context_practice_id,
    p.name AS practice_name,
    p.logo AS practice_logo,
    p.city AS practice_city,
    p.street_address AS practice_street_address,
    p.phone AS practice_phone,
    p.email AS practice_email,
    p.website AS practice_website,
    p.practice_code,
    p.instagram AS practice_instagram,
    p.facebook AS practice_facebook,
    p.has_multiple_providers,
    p.practice_category,
    p.specialty AS practice_specialty,
    p.is_suspended,
    s.status AS subscription_status,
    s.plan AS subscription_plan,
    s."trialEnd" AS subscription_trial_end,
    s."periodEnd" AS subscription_period_end,
    s."cancelAt" AS subscription_cancel_at
FROM users u
LEFT JOIN practices p ON p.id = u.practice_id
LEFT JOIN subscription s ON s."referenceId" = u.practice_id::text
WHERE u.id = $1
`

type GetCurrentUserContextRow struct {
	ID                    uuid.UUID
	Email                 *string
	FirstName             string
	LastName              string
	AvatarUrl             *string
	PracticeID            *uuid.UUID
	Role                  *string
	IsActive              bool
	DeletedAt             *time.Time
	ContextPracticeID     *uuid.UUID
	PracticeName          *string
	PracticeLogo          *string
	PracticeCity          *string
	PracticeStreetAddress *string
	PracticePhone         *string
	PracticeEmail         *string
	PracticeWebsite       *string
	PracticeCode          *string
	PracticeInstagram     *string
	PracticeFacebook      *string
	HasMultipleProviders  *bool
	PracticeCategory      *string
	PracticeSpecialty     *string
	IsSuspended           *bool
	SubscriptionStatus    *string
	SubscriptionPlan      *string
	SubscriptionTrialEnd  pgtype.Timestamptz
	SubscriptionPeriodEnd pgtype.Timestamptz
	SubscriptionCancelAt  pgtype.Timestamptz
}

func (q *Queries) GetCurrentUserContext(ctx context.Context, id uuid.UUID) (GetCurrentUserContextRow, error) {
	row := q.db.QueryRow(ctx, getCurrentUserContext, id)
	var i GetCurrentUserContextRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.PracticeID,
		&i.Role,
		&i.IsActive,
		&i.DeletedAt,
		&i.ContextPracticeID,
		&i.PracticeName,
		&i.PracticeLogo,
		&i.PracticeCity,
		&i.PracticeStreetAddress,
		&i.PracticePhone,
		&i.PracticeEmail,
		&i.PracticeWebsite,
		&i.PracticeCode,
		&i.PracticeInstagram,
		&i.PracticeFacebook,
		&i.HasMultipleProviders,
		&i.PracticeCategory,
		&i.PracticeSpecialty,
		&i.IsSuspended,
		&i.SubscriptionStatus,
		&i.SubscriptionPlan,
		&i.SubscriptionTrialEnd,
		&i.SubscriptionPeriodEnd,
		&i.SubscriptionCancelAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserAuthorization = `-- name: GetUserAuthorization :one
SELECT u.id, u.email, u.first_name, u.last_name, u.practice_id,
       u.role, u.is_active, u.deleted_at, p.is_suspended
FROM users u
JOIN practices p ON p.id = u.practice_id
WHERE u.id = $1
`

type GetUserAuthorizationRow struct {
	ID          uuid.UUID
	Email       *string
	FirstName   string
	LastName    string
	PracticeID  *uuid.UUID
	Role        *string
	IsActive    bool
	DeletedAt   *time.Time
	IsSuspended bool
}

func (q *Queries) GetUserAuthorization(ctx context.Context, id uuid.UUID) (GetUserAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthorization, id)
	var i GetUserAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PracticeID,
		&i.Role,
		&i.IsActive,
		&i.DeletedAt,
		&i.IsSuspended,
	)
	return i, err
}

const getUserWithSubscriptionStatus = `-- name: GetUserWithSubscriptionStatus :one
SELECT
    u.id, u.created_at, u.modified_at, u.first_name, u.last_name, u.mobile_phone, u.email, u.practice_id, u.role, u.org_role, u.is_active, u.invited_by, u.avatar_url, u.whatsapp_notifications_enabled, u.terms_agreed_at, u.deleted_at,
    p.is_suspended AS practice_is_suspended,
    s.status AS subscription_status,
    s."trialEnd" AS subscription_trial_end,
    s."periodEnd" AS subscription_period_end,
    s.plan AS subscription_plan,
    s."cancelAt" AS subscription_cancel_at
FROM users u
LEFT JOIN practices p ON p.id = u.practice_id
LEFT JOIN subscription s ON s."referenceId" = u.practice_id::text
WHERE u.id = $1
`

type GetUserWithSubscriptionStatusRow struct {
	ID                           uuid.UUID
	CreatedAt                    *time.Time
	ModifiedAt                   *time.Time
	FirstName                    string
	LastName                     string
	MobilePhone                  *string
	Email                        *string
	PracticeID                   *uuid.UUID
	Role                         *string
	OrgRole                      *string
	IsActive                     bool
	InvitedBy                    *uuid.UUID
	AvatarUrl                    *string
	WhatsappNotificationsEnabled bool
	TermsAgreedAt                *time.Time
	DeletedAt                    *time.Time
	PracticeIsSuspended          *bool
	SubscriptionStatus           *string
	SubscriptionTrialEnd         pgtype.Timestamptz
	SubscriptionPeriodEnd        pgtype.Timestamptz
	SubscriptionPlan             *string
	SubscriptionCancelAt         pgtype.Timestamptz
}

func (q *Queries) GetUserWithSubscriptionStatus(ctx context.Context, id uuid.UUID) (GetUserWithSubscriptionStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserWithSubscriptionStatus, id)
	var i GetUserWithSubscriptionStatusRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
		&i.PracticeIsSuspended,
		&i.SubscriptionStatus,
		&i.SubscriptionTrialEnd,
		&i.SubscriptionPeriodEnd,
		&i.SubscriptionPlan,
		&i.SubscriptionCancelAt,
	)
	return i, err
}

const hardDeleteTestUser = `-- name: HardDeleteTestUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) HardDeleteTestUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteTestUser, id)
	return err
}

const updateAccount = `-- name: UpdateAccount :execrows
UPDATE users
SET
    first_name = $1,
    last_name = $2,
    avatar_url = $3,
    mobile_phone = CASE
        WHEN $4::boolean THEN $5::text
        ELSE mobile_phone
    END,
    whatsapp_notifications_enabled = CASE
        WHEN $6::boolean
            THEN $7::boolean
        ELSE whatsapp_notifications_enabled
    END
WHERE id = $8
`

type UpdateAccountParams struct {
	FirstName                       string
	LastName                        string
	AvatarUrl                       *string
	SetMobilePhone                  bool
	MobilePhone                     *string
	SetWhatsappNotificationsEnabled bool
	WhatsappNotificationsEnabled    bool
	ID                              uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccount,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.SetMobilePhone,
		arg.MobilePhone,
		arg.SetWhatsappNotificationsEnabled,
		arg.WhatsappNotificationsEnabled,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    email = COALESCE($3, email),
    mobile_phone = COALESCE($4, mobile_phone),
    role = COALESCE($5, role),
    org_role = COALESCE($6, org_role),
    is_active = COALESCE($7, is_active),
    avatar_url = COALESCE($8, avatar_url),
    whatsapp_notifications_enabled = COALESCE($9, whatsapp_notifications_enabled),
    terms_agreed_at = COALESCE($10, terms_agreed_at),
    modified_at = NOW()
WHERE id = $11
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at
`

type UpdateUserParams struct {
	FirstName                    *string
	LastName                     *string
	Email                        *string
	MobilePhone                  *string
	Role                         *string
	OrgRole                      *string
	IsActive                     *bool
	AvatarUrl                    *string
	WhatsappNotificationsEnabled *bool
	TermsAgreedAt                *time.Time
	ID                           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
		arg.Role,
		arg.OrgRole,
		arg.IsActive,
		arg.AvatarUrl,
		arg.WhatsappNotificationsEnabled,
		arg.TermsAgreedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPracticeID = `-- name: UpdateUserPracticeID :one
UPDATE users
SET practice_id = $1
WHERE id = $2
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, org_role, is_active, invited_by, avatar_url, whatsapp_notifications_enabled, terms_agreed_at, deleted_at
`

type UpdateUserPracticeIDParams struct {
	PracticeID *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateUserPracticeID(ctx context.Context, arg UpdateUserPracticeIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPracticeID, arg.PracticeID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.OrgRole,
		&i.IsActive,
		&i.InvitedBy,
		&i.AvatarUrl,
		&i.WhatsappNotificationsEnabled,
		&i.TermsAgreedAt,
		&i.DeletedAt,
	)
	return i, err
}
