package server

import (
	"archive/zip"
	"bytes"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"net/http"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/gin-gonic/gin"
	db "github.com/mentalcaries/connectient-api/internal/database"
)

const (
	appointmentExportLimit      = 10000
	appointmentExportByteLimit  = 50 << 20
	registrationExportLimit     = 1000
	registrationExportJSONLimit = 25 << 20
	docxContentType             = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
)

type exportDocumentParagraph struct {
	style     string
	label     string
	value     string
	pageBreak bool
}

func (s *Server) handlerExportAppointments(c *gin.Context) {
	setPrivateNoStore(c)
	user := c.MustGet("user").(AuthUser)
	rows, err := s.DBQuery.ListAppointmentExportRows(c, *user.PracticeId)
	if err != nil {
		respondWithError(c, http.StatusInternalServerError, "Failed to export appointments", err)
		return
	}
	if len(rows) > appointmentExportLimit {
		c.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "Appointment export exceeds the 10000 row limit"})
		return
	}
	now := time.Now()
	payload, err := renderAppointmentCSV(rows, now)
	if err != nil {
		respondWithError(c, http.StatusInternalServerError, "Failed to export appointments", err)
		return
	}
	if len(payload) > appointmentExportByteLimit {
		c.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "Appointment export exceeds the 50 MiB data limit"})
		return
	}
	if err := s.recordDataExport(c, user, "appointments", len(rows)); err != nil {
		respondWithError(c, http.StatusInternalServerError, "Failed to audit appointment export", err)
		return
	}
	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="appointments-%s.csv"`, now.Format("02-01-2006")))
	c.Data(http.StatusOK, "text/csv; charset=utf-8", payload)
}

func (s *Server) handlerExportRegistrations(c *gin.Context) {
	setPrivateNoStore(c)
	user := c.MustGet("user").(AuthUser)
	rows, err := s.DBQuery.ListRegistrationExportRows(c, *user.PracticeId)
	if err != nil {
		respondWithError(c, http.StatusInternalServerError, "Failed to export registrations", err)
		return
	}
	if len(rows) > registrationExportLimit {
		c.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "Registration export exceeds the 1000 row limit"})
		return
	}
	totalJSON := 0
	for _, row := range rows {
		totalJSON += len(row.FormData)
		if totalJSON > registrationExportJSONLimit {
			c.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "Registration export exceeds the 25 MiB data limit"})
			return
		}
	}
	now := time.Now()
	payload, err := renderRegistrationDOCX(rows, now)
	if err != nil {
		respondWithError(c, http.StatusInternalServerError, "Failed to export registrations", err)
		return
	}
	if err := s.recordDataExport(c, user, "registrations", len(rows)); err != nil {
		respondWithError(c, http.StatusInternalServerError, "Failed to audit registration export", err)
		return
	}
	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="registrations-%s.docx"`, now.Format("2006-01-02")))
	c.Data(http.StatusOK, docxContentType, payload)
}

func (s *Server) recordDataExport(c *gin.Context, user AuthUser, exportType string, count int) error {
	return s.DBQuery.CreateDataExportAuditLog(c, db.CreateDataExportAuditLogParams{
		PracticeID: *user.PracticeId, ExportedByUserID: user.ID,
		ExportType: exportType, RowCount: int32(count),
	})
}

func renderAppointmentCSV(rows []db.ListAppointmentExportRowsRow, now time.Time) ([]byte, error) {
	var output bytes.Buffer
	writer := csv.NewWriter(&output)
	if err := writer.Write([]string{
		"Patient First Name", "Patient Last Name", "Email", "Phone", "Appointment Type",
		"Requested Date", "Status", "Location", "Notes", "Submitted At",
	}); err != nil {
		return nil, err
	}
	for _, row := range rows {
		status := "Pending"
		if row.IsCancelled {
			status = "Cancelled"
		} else if row.IsScheduled {
			status = "Scheduled"
		}
		requestedDate := ""
		if row.RequestedDate != nil {
			requestedDate = row.RequestedDate.Format("02-01-2006")
		}
		values := []string{
			row.FirstName, row.LastName, row.Email, row.MobilePhone, pointerString(row.AppointmentType),
			requestedDate, status, pointerString(row.LocationName), pointerString(row.Description),
			row.CreatedAt.Format("02-01-2006 15:04:05"),
		}
		for index := range values {
			values[index] = protectSpreadsheetCell(values[index])
		}
		if err := writer.Write(values); err != nil {
			return nil, err
		}
	}
	if err := writer.Write(nil); err != nil {
		return nil, err
	}
	if err := writer.Write([]string{"", "Generated by Connectient(https://connectient.app) on " + now.Format("02-01-2006 15:04:05")}); err != nil {
		return nil, err
	}
	writer.Flush()
	if err := writer.Error(); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func protectSpreadsheetCell(value string) string {
	trimmed := strings.TrimLeftFunc(value, func(value rune) bool {
		return unicode.IsSpace(value) && value != '\t' && value != '\r' && value != '\n'
	})
	if trimmed == "" {
		return value
	}
	switch trimmed[0] {
	case '=', '+', '-', '@', '\t', '\r', '\n':
		return "'" + value
	default:
		return value
	}
}

func renderRegistrationDOCX(rows []db.ListRegistrationExportRowsRow, now time.Time) ([]byte, error) {
	paragraphs := make([]exportDocumentParagraph, 0, len(rows)*30)
	for index, row := range rows {
		contact := pointerString(row.PatientEmail)
		if contact == "" {
			contact = pointerString(row.PatientPhone)
		}
		heading := row.PatientName
		if contact != "" {
			heading += " - " + contact
		}
		paragraphs = append(paragraphs, exportDocumentParagraph{style: "Heading2", value: heading})
		submitted := "—"
		if row.CompletedAt != nil {
			submitted = row.CompletedAt.Format("2 January 2006")
		}
		paragraphs = append(paragraphs,
			exportDocumentParagraph{label: "Submission Date: ", value: submitted},
			exportDocumentParagraph{label: "Form Version: ", value: displayExportValue(row.FormVersion)},
		)
		var formData map[string]any
		decoder := json.NewDecoder(bytes.NewReader(row.FormData))
		decoder.UseNumber()
		if err := decoder.Decode(&formData); err != nil {
			return nil, fmt.Errorf("registration %s form data: %w", row.ID, err)
		}
		appendRegistrationSections(&paragraphs, formData)
		if index < len(rows)-1 {
			paragraphs = append(paragraphs, exportDocumentParagraph{pageBreak: true})
		}
	}
	return buildDOCX(paragraphs, "Generated by Connectient (https://connectient.app)", now.Format("2 January 2006 15:04:05"))
}

var registrationSectionOrder = []struct {
	key   string
	title string
}{
	{"personal", "Personal Details"},
	{"additional", "Additional Information"},
	{"medical_history", "Medical History"},
	{"dental_history", "Dental History"},
	{"physiotherapy_history", "Physiotherapy History"},
	{"optometry_history", "Optometry History"},
	{"signature", "Signature"},
}

func appendRegistrationSections(paragraphs *[]exportDocumentParagraph, formData map[string]any) {
	known := make(map[string]bool, len(registrationSectionOrder))
	for _, section := range registrationSectionOrder {
		known[section.key] = true
		value, exists := formData[section.key]
		if !exists {
			continue
		}
		*paragraphs = append(*paragraphs, exportDocumentParagraph{style: "Heading3", value: section.title})
		appendExportFields(paragraphs, "", value)
	}
	unknown := make([]string, 0)
	for key := range formData {
		if !known[key] {
			unknown = append(unknown, key)
		}
	}
	sort.Strings(unknown)
	for _, key := range unknown {
		*paragraphs = append(*paragraphs, exportDocumentParagraph{style: "Heading3", value: exportLabel(key)})
		appendExportFields(paragraphs, "", formData[key])
	}
}

func appendExportFields(paragraphs *[]exportDocumentParagraph, prefix string, value any) {
	if object, ok := value.(map[string]any); ok {
		keys := make([]string, 0, len(object))
		for key := range object {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			label := exportLabel(key)
			if prefix != "" {
				label = prefix + " - " + label
			}
			if _, nested := object[key].(map[string]any); nested {
				appendExportFields(paragraphs, label, object[key])
				continue
			}
			*paragraphs = append(*paragraphs, exportDocumentParagraph{label: label + ": ", value: displayExportValue(object[key])})
		}
		if len(keys) == 0 {
			*paragraphs = append(*paragraphs, exportDocumentParagraph{value: "—"})
		}
		return
	}
	*paragraphs = append(*paragraphs, exportDocumentParagraph{value: displayExportValue(value)})
}

func displayExportValue(value any) string {
	switch typed := value.(type) {
	case nil:
		return "—"
	case bool:
		if typed {
			return "Yes"
		}
		return "No"
	case string:
		if typed == "" {
			return "—"
		}
		return typed
	case json.Number:
		return typed.String()
	case []any:
		if len(typed) == 0 {
			return "—"
		}
		parts := make([]string, len(typed))
		for index, item := range typed {
			parts[index] = displayExportValue(item)
		}
		return strings.Join(parts, ", ")
	default:
		encoded, err := json.Marshal(typed)
		if err != nil {
			return "—"
		}
		return string(encoded)
	}
}

func exportLabel(key string) string {
	words := strings.Fields(strings.ReplaceAll(key, "_", " "))
	for index, word := range words {
		switch strings.ToLower(word) {
		case "hiv":
			words[index] = "HIV"
		case "tmj":
			words[index] = "TMJ"
		case "xray", "xrays":
			words[index] = "X-rays"
		default:
			runes := []rune(strings.ToLower(word))
			if len(runes) > 0 {
				runes[0] = unicode.ToUpper(runes[0])
			}
			words[index] = string(runes)
		}
	}
	return strings.Join(words, " ")
}

func buildDOCX(paragraphs []exportDocumentParagraph, footerLeft, footerRight string) ([]byte, error) {
	var output bytes.Buffer
	archive := zip.NewWriter(&output)
	files := map[string]string{
		"[Content_Types].xml":          `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>`,
		"_rels/.rels":                  `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`,
		"word/_rels/document.xml.rels": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,
		"word/styles.xml":              `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="24"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading3"><w:name w:val="heading 3"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="26"/></w:rPr></w:style></w:styles>`,
		"word/document.xml":            buildDocumentXML(paragraphs),
		"word/footer1.xml":             `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:p><w:pPr><w:tabs><w:tab w:val="right" w:pos="9026"/></w:tabs></w:pPr>` + docxRun(footerLeft, false) + docxRun("\t"+footerRight, false) + `</w:p></w:ftr>`,
	}
	order := []string{"[Content_Types].xml", "_rels/.rels", "word/document.xml", "word/styles.xml", "word/_rels/document.xml.rels", "word/footer1.xml"}
	for _, name := range order {
		writer, err := archive.Create(name)
		if err != nil {
			return nil, err
		}
		if _, err := writer.Write([]byte(files[name])); err != nil {
			return nil, err
		}
	}
	if err := archive.Close(); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func buildDocumentXML(paragraphs []exportDocumentParagraph) string {
	var document strings.Builder
	document.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>`)
	for _, paragraph := range paragraphs {
		if paragraph.pageBreak {
			document.WriteString(`<w:p><w:r><w:br w:type="page"/></w:r></w:p>`)
			continue
		}
		document.WriteString(`<w:p>`)
		if paragraph.style != "" {
			document.WriteString(`<w:pPr><w:pStyle w:val="` + xmlEscape(paragraph.style) + `"/></w:pPr>`)
		}
		if paragraph.label != "" {
			document.WriteString(docxRun(paragraph.label, true))
		}
		document.WriteString(docxRun(paragraph.value, false))
		document.WriteString(`</w:p>`)
	}
	document.WriteString(`<w:sectPr><w:footerReference w:type="default" r:id="rId1"/><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:footer="720"/></w:sectPr></w:body></w:document>`)
	return document.String()
}

func docxRun(value string, bold bool) string {
	if value == "" {
		return ""
	}
	parts := strings.Split(strings.ReplaceAll(value, "\r\n", "\n"), "\n")
	var run strings.Builder
	run.WriteString(`<w:r>`)
	if bold {
		run.WriteString(`<w:rPr><w:b/></w:rPr>`)
	}
	for index, part := range parts {
		if index > 0 {
			run.WriteString(`<w:br/>`)
		}
		run.WriteString(`<w:t xml:space="preserve">` + xmlEscape(part) + `</w:t>`)
	}
	run.WriteString(`</w:r>`)
	return run.String()
}

func xmlEscape(value string) string {
	replacer := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return replacer.Replace(value)
}
