package server

import (
	"archive/zip"
	"bytes"
	"encoding/xml"
	"io"
	"strings"
	"testing"
	"time"

	db "github.com/mentalcaries/connectient-api/internal/database"
)

func TestRenderAppointmentCSVGolden(t *testing.T) {
	requested := time.Date(2026, 10, 9, 0, 0, 0, 0, time.UTC)
	created := time.Date(2026, 10, 7, 14, 5, 6, 0, time.UTC)
	appointmentType, location, description := "=IMPORTXML(A1)", "Main, Office", "Line one\nLine two"
	payload, err := renderAppointmentCSV([]db.ListAppointmentExportRowsRow{{
		FirstName: "Jane", LastName: "Doe", Email: "@unsafe.example", MobilePhone: "+15550000000",
		AppointmentType: &appointmentType, RequestedDate: &requested, IsScheduled: true,
		LocationName: &location, Description: &description, CreatedAt: created,
	}}, time.Date(2026, 10, 7, 15, 6, 7, 0, time.UTC))
	if err != nil {
		t.Fatal(err)
	}
	want := "Patient First Name,Patient Last Name,Email,Phone,Appointment Type,Requested Date,Status,Location,Notes,Submitted At\n" +
		"Jane,Doe,'@unsafe.example,'+15550000000,'=IMPORTXML(A1),09-10-2026,Scheduled,\"Main, Office\",\"Line one\nLine two\",07-10-2026 14:05:06\n" +
		"\n,Generated by Connectient(https://connectient.app) on 07-10-2026 15:06:07\n"
	if string(payload) != want {
		t.Errorf("CSV mismatch\nwant:\n%s\ngot:\n%s", want, payload)
	}
}

func TestRenderRegistrationDOCXGolden(t *testing.T) {
	completed := time.Date(2026, 10, 7, 12, 0, 0, 0, time.UTC)
	email := "jane@example.test"
	form := []byte(`{
		"personal":{"first_name":"Jane & Co","email_contact_ok":true},
		"additional":{"emergency_contact_name":"Parent"},
		"medical_history":{"conditions":["Asthma","Diabetes"],"hiv_contact":false},
		"dental_history":{"tmj":{"jaw_pain":true}},
		"physiotherapy_history":{"pain_level":7},
		"optometry_history":{"corrective_lenses":"glasses"},
		"signature":{"signed_by":"Jane Doe","relationship":"Self","signature_data":"Jane <Doe>","signed_at":"2026-10-07T12:00:00Z"},
		"custom_section":{"custom_answer":"Value"}
	}`)
	payload, err := renderRegistrationDOCX([]db.ListRegistrationExportRowsRow{{
		PatientName: "Jane Doe", PatientEmail: &email, CompletedAt: &completed,
		FormVersion: "medical-dental-physio-optometry-v1", FormData: form,
	}}, time.Date(2026, 10, 7, 13, 30, 0, 0, time.UTC))
	if err != nil {
		t.Fatal(err)
	}
	text, names := readDOCXText(t, payload)
	for _, name := range []string{"[Content_Types].xml", "_rels/.rels", "word/document.xml", "word/styles.xml", "word/footer1.xml"} {
		if !names[name] {
			t.Errorf("DOCX missing %s", name)
		}
	}
	for _, expected := range []string{
		"Jane Doe - jane@example.test", "Submission Date: 7 October 2026",
		"Form Version: medical-dental-physio-optometry-v1", "Personal Details",
		"First Name: Jane & Co", "Email Contact Ok: Yes", "Medical History",
		"Conditions: Asthma, Diabetes", "HIV Contact: No", "Dental History",
		"TMJ - Jaw Pain: Yes", "Physiotherapy History", "Pain Level: 7",
		"Optometry History", "Corrective Lenses: glasses", "Signature",
		"Signature Data: Jane <Doe>", "Custom Section", "Custom Answer: Value",
	} {
		if !strings.Contains(text, expected) {
			t.Errorf("DOCX text missing %q in %q", expected, text)
		}
	}
}

func TestRenderRegistrationDOCXRejectsInvalidJSON(t *testing.T) {
	_, err := renderRegistrationDOCX([]db.ListRegistrationExportRowsRow{{FormData: []byte(`{`)}}, time.Now())
	if err == nil {
		t.Fatal("invalid registration JSON accepted")
	}
}

func TestProtectSpreadsheetCell(t *testing.T) {
	for _, value := range []string{"=formula", "+1555", "-1", "@name", " \tformula"} {
		if got := protectSpreadsheetCell(value); !strings.HasPrefix(got, "'") {
			t.Errorf("unsafe cell %q was not protected: %q", value, got)
		}
	}
	if got := protectSpreadsheetCell("ordinary"); got != "ordinary" {
		t.Errorf("ordinary cell changed to %q", got)
	}
}

func readDOCXText(t *testing.T, payload []byte) (string, map[string]bool) {
	t.Helper()
	archive, err := zip.NewReader(bytes.NewReader(payload), int64(len(payload)))
	if err != nil {
		t.Fatal(err)
	}
	names := make(map[string]bool, len(archive.File))
	var text strings.Builder
	for _, file := range archive.File {
		names[file.Name] = true
		if file.Name != "word/document.xml" && file.Name != "word/footer1.xml" {
			continue
		}
		reader, err := file.Open()
		if err != nil {
			t.Fatal(err)
		}
		decoder := xml.NewDecoder(reader)
		for {
			token, err := decoder.Token()
			if err == io.EOF {
				break
			}
			if err != nil {
				reader.Close()
				t.Fatal(err)
			}
			start, ok := token.(xml.StartElement)
			if !ok || start.Name.Local != "t" {
				continue
			}
			var value string
			if err := decoder.DecodeElement(&value, &start); err != nil {
				reader.Close()
				t.Fatal(err)
			}
			text.WriteString(value)
		}
		reader.Close()
	}
	return text.String(), names
}
